LEGAL_STATES_DAYS_ARRAY = [
          { credit_entity: 'DAVIVIENDA', subsidy_entity: 'SIN SUBSIDIO', days: 15, legal_state: 'PREAPROB Y CONSEC'},
          { credit_entity: 'DAVIVIENDA', subsidy_entity: 'SIN SUBSIDIO', days: 15, legal_state: 'TRAMITE'},
          { credit_entity: 'DAVIVIENDA', subsidy_entity: 'SIN SUBSIDIO', days: nil, legal_state: 'APROBADO'},
          { credit_entity: 'DAVIVIENDA', subsidy_entity: 'SIN SUBSIDIO', days: 8, legal_state: 'CARTA DE NOVEDAD'},
          { credit_entity: 'DAVIVIENDA', subsidy_entity: 'SIN SUBSIDIO', days: 0, legal_state: 'AVALUO PRELIMINAR'},
          { credit_entity: 'DAVIVIENDA', subsidy_entity: 'SIN SUBSIDIO', days: 3, legal_state: 'AVALUO FINAL'},
          { credit_entity: 'DAVIVIENDA', subsidy_entity: 'SIN SUBSIDIO', days: 3, legal_state: 'ELAB ESCRITURACION'},
          { credit_entity: 'DAVIVIENDA', subsidy_entity: 'SIN SUBSIDIO', days: 5, legal_state: 'REVISION FIDUCIA'},
          { credit_entity: 'DAVIVIENDA', subsidy_entity: 'SIN SUBSIDIO', days: 5, legal_state: 'FIRMA ESC. CLIENTE'},
          { credit_entity: 'DAVIVIENDA', subsidy_entity: 'SIN SUBSIDIO', days: 2, legal_state: 'NUMERACION ESCRITURA'},
          { credit_entity: 'DAVIVIENDA', subsidy_entity: 'SIN SUBSIDIO', days: 1, legal_state: 'FIRMA ESC. CONSTRUCTORA' },
          { credit_entity: 'DAVIVIENDA', subsidy_entity: 'SIN SUBSIDIO', days: 3, legal_state: 'ESTUDIO TITULOS'},
          { credit_entity: 'DAVIVIENDA', subsidy_entity: 'SIN SUBSIDIO', days: 2, legal_state: 'FIRMA FIDUCIA'},
          { credit_entity: 'DAVIVIENDA', subsidy_entity: 'SIN SUBSIDIO', days: 2, legal_state: 'FIRMA BANCO'},
          { credit_entity: 'DAVIVIENDA', subsidy_entity: 'SIN SUBSIDIO', days: 7, legal_state: 'PROTOCOLIZACION'},
          { credit_entity: 'DAVIVIENDA', subsidy_entity: 'SIN SUBSIDIO', days: 0, legal_state: 'LIQUIDACION'},
          { credit_entity: 'DAVIVIENDA', subsidy_entity: 'SIN SUBSIDIO', days: 3, legal_state: 'ENTRADA DE REGISTRO'},
          { credit_entity: 'DAVIVIENDA', subsidy_entity: 'SIN SUBSIDIO', days: 5, legal_state: 'RADICADO EN ESPERA DE DESEMBOLSO'},
          { credit_entity: 'DAVIVIENDA', subsidy_entity: 'SIN SUBSIDIO', days: 3, legal_state: 'ENTREGA DE VIVIENDA'},
          { credit_entity: 'DAVIVIENDA', subsidy_entity: 'SUBSIDIO CAJA', days: 15, legal_state: 'PREAPROB Y CONSEC'},
          { credit_entity: 'DAVIVIENDA', subsidy_entity: 'SUBSIDIO CAJA', days: 15, legal_state: 'TRAMITE'},
          { credit_entity: 'DAVIVIENDA', subsidy_entity: 'SUBSIDIO CAJA', days: nil, legal_state: 'APROBADO'},
          { credit_entity: 'DAVIVIENDA', subsidy_entity: 'SUBSIDIO CAJA', days: 8, legal_state: 'CARTA DE NOVEDAD'},
          { credit_entity: 'DAVIVIENDA', subsidy_entity: 'SUBSIDIO CAJA', days: 0, legal_state: 'AVALUO PRELIMINAR'},
          { credit_entity: 'DAVIVIENDA', subsidy_entity: 'SUBSIDIO CAJA', days: 3, legal_state: 'AVALUO FINAL'},
          { credit_entity: 'DAVIVIENDA', subsidy_entity: 'SUBSIDIO CAJA', days: 3, legal_state: 'ELAB ESCRITURACION'},
          { credit_entity: 'DAVIVIENDA', subsidy_entity: 'SUBSIDIO CAJA', days: 5, legal_state: 'REVISION FIDUCIA'},
          { credit_entity: 'DAVIVIENDA', subsidy_entity: 'SUBSIDIO CAJA', days: 5, legal_state: 'FIRMA ESC. CLIENTE'},
          { credit_entity: 'DAVIVIENDA', subsidy_entity: 'SUBSIDIO CAJA', days: 2, legal_state: 'NUMERACION ESCRITURA'},
          { credit_entity: 'DAVIVIENDA', subsidy_entity: 'SUBSIDIO CAJA', days: 1, legal_state: 'FIRMA ESC. CONSTRUCTORA'},
          { credit_entity: 'DAVIVIENDA', subsidy_entity: 'SUBSIDIO CAJA', days: 3, legal_state: 'ESTUDIO TITULOS'},
          { credit_entity: 'DAVIVIENDA', subsidy_entity: 'SUBSIDIO CAJA', days: 2, legal_state: 'FIRMA FIDUCIA'},
          { credit_entity: 'DAVIVIENDA', subsidy_entity: 'SUBSIDIO CAJA', days: 2, legal_state: 'FIRMA BANCO'},
          { credit_entity: 'DAVIVIENDA', subsidy_entity: 'SUBSIDIO CAJA', days: 7, legal_state: 'PROTOCOLIZACION'},
          { credit_entity: 'DAVIVIENDA', subsidy_entity: 'SUBSIDIO CAJA', days: 0, legal_state: 'LIQUIDACION'},
          { credit_entity: 'DAVIVIENDA', subsidy_entity: 'SUBSIDIO CAJA', days: 3, legal_state: 'ENTRADA DE REGISTRO'},
          { credit_entity: 'DAVIVIENDA', subsidy_entity: 'SUBSIDIO CAJA', days: 5, legal_state: 'RADICADO EN ESPERA DE DESEMBOLSO'},
          { credit_entity: 'DAVIVIENDA', subsidy_entity: 'SUBSIDIO CAJA', days: 3, legal_state: 'ENTREGA DE VIVIENDA'},
          { credit_entity: 'DAVIVIENDA', subsidy_entity: 'SUBSIDIO CAJA', days: 10, legal_state: 'ESCRITURA EN REGISTRO'},
          { credit_entity: 'DAVIVIENDA', subsidy_entity: 'SUBSIDIO CAJA', days: 0, legal_state: 'ACLARATORIA AL SUBSIDIO'},
          { credit_entity: 'DAVIVIENDA', subsidy_entity: 'SUBSIDIO CAJA', days: 19, legal_state: 'SUBSIDIO RADICADO'},
          { credit_entity: 'DAVIVIENDA', subsidy_entity: 'MCY', days: 15, legal_state: 'PREAPROB Y CONSEC'},
          { credit_entity: 'DAVIVIENDA', subsidy_entity: 'MCY', days: 15, legal_state: 'TRAMITE'},
          { credit_entity: 'DAVIVIENDA', subsidy_entity: 'MCY', days: nil, legal_state: 'APROBADO'},
          { credit_entity: 'DAVIVIENDA', subsidy_entity: 'MCY', days: 8, legal_state: 'CARTA DE NOVEDAD'},
          { credit_entity: 'DAVIVIENDA', subsidy_entity: 'MCY', days: 0, legal_state: 'AVALUO PRELIMINAR'},
          { credit_entity: 'DAVIVIENDA', subsidy_entity: 'MCY', days: 3, legal_state: 'AVALUO FINAL'},
          { credit_entity: 'DAVIVIENDA', subsidy_entity: 'MCY', days: 18, legal_state: 'EN ESPERA DE RESOLUCION MCY (PROCESO 027)'},
          { credit_entity: 'DAVIVIENDA', subsidy_entity: 'MCY', days: 3, legal_state: 'ELAB ESCRITURACION'},
          { credit_entity: 'DAVIVIENDA', subsidy_entity: 'MCY', days: 5, legal_state: 'REVISION FIDUCIA'},
          { credit_entity: 'DAVIVIENDA', subsidy_entity: 'MCY', days: 5, legal_state: 'FIRMA ESC. CLIENTE'},
          { credit_entity: 'DAVIVIENDA', subsidy_entity: 'MCY', days: 2, legal_state: 'NUMERACION ESCRITURA'},
          { credit_entity: 'DAVIVIENDA', subsidy_entity: 'MCY', days: 1, legal_state: 'FIRMA ESC. CONSTRUCTORA'},
          { credit_entity: 'DAVIVIENDA', subsidy_entity: 'MCY', days: 3, legal_state: 'ESTUDIO TITULOS'},
          { credit_entity: 'DAVIVIENDA', subsidy_entity: 'MCY', days: 2, legal_state: 'FIRMA FIDUCIA'},
          { credit_entity: 'DAVIVIENDA', subsidy_entity: 'MCY', days: 2, legal_state: 'FIRMA BANCO'},
          { credit_entity: 'DAVIVIENDA', subsidy_entity: 'MCY', days: 7, legal_state: 'PROTOCOLIZACION'},
          { credit_entity: 'DAVIVIENDA', subsidy_entity: 'MCY', days: 0, legal_state: 'LIQUIDACION'},
          { credit_entity: 'DAVIVIENDA', subsidy_entity: 'MCY', days: 3, legal_state: 'ENTRADA DE REGISTRO'},
          { credit_entity: 'DAVIVIENDA', subsidy_entity: 'MCY', days: 5, legal_state: 'RADICADO EN ESPERA DE DESEMBOLSO'},
          { credit_entity: 'DAVIVIENDA', subsidy_entity: 'MCY', days: 0, legal_state: 'ESCRITURA EN REGISTRO'},
          { credit_entity: 'DAVIVIENDA', subsidy_entity: 'MCY', days: 28, legal_state: 'SUBSIDIO RADICADO'},
          { credit_entity: 'DAVIVIENDA', subsidy_entity: 'MCY', days: 3, legal_state: 'ENTREGA DE VIVIENDA'},
          { credit_entity: 'DAVIVIENDA', subsidy_entity: 'SUBSIDIO CAJA Y MCY', days: 15, legal_state: 'PREAPROB Y CONSEC'},
          { credit_entity: 'DAVIVIENDA', subsidy_entity: 'SUBSIDIO CAJA Y MCY', days: 15, legal_state: 'TRAMITE'},
          { credit_entity: 'DAVIVIENDA', subsidy_entity: 'SUBSIDIO CAJA Y MCY', days: nil, legal_state: 'APROBADO'},
          { credit_entity: 'DAVIVIENDA', subsidy_entity: 'SUBSIDIO CAJA Y MCY', days: 8, legal_state: 'CARTA DE NOVEDAD'},
          { credit_entity: 'DAVIVIENDA', subsidy_entity: 'SUBSIDIO CAJA Y MCY', days: 0, legal_state: 'AVALUO PRELIMINAR'},
          { credit_entity: 'DAVIVIENDA', subsidy_entity: 'SUBSIDIO CAJA Y MCY', days: 3, legal_state: 'AVALUO FINAL'},
          { credit_entity: 'DAVIVIENDA', subsidy_entity: 'SUBSIDIO CAJA Y MCY', days: 18, legal_state: 'EN ESPERA DE RESOLUCION MCY (PROCESO 027)'},
          { credit_entity: 'DAVIVIENDA', subsidy_entity: 'SUBSIDIO CAJA Y MCY', days: 3, legal_state: 'ELAB ESCRITURACION'},
          { credit_entity: 'DAVIVIENDA', subsidy_entity: 'SUBSIDIO CAJA Y MCY', days: 5, legal_state: 'REVISION FIDUCIA'},
          { credit_entity: 'DAVIVIENDA', subsidy_entity: 'SUBSIDIO CAJA Y MCY', days: 5, legal_state: 'FIRMA ESC. CLIENTE'},
          { credit_entity: 'DAVIVIENDA', subsidy_entity: 'SUBSIDIO CAJA Y MCY', days: 2, legal_state: 'NUMERACION ESCRITURA'},
          { credit_entity: 'DAVIVIENDA', subsidy_entity: 'SUBSIDIO CAJA Y MCY', days: 1, legal_state: 'FIRMA ESC. CONSTRUCTORA'},
          { credit_entity: 'DAVIVIENDA', subsidy_entity: 'SUBSIDIO CAJA Y MCY', days: 3, legal_state: 'ESTUDIO TITULOS'},
          { credit_entity: 'DAVIVIENDA', subsidy_entity: 'SUBSIDIO CAJA Y MCY', days: 2, legal_state: 'FIRMA FIDUCIA'},
          { credit_entity: 'DAVIVIENDA', subsidy_entity: 'SUBSIDIO CAJA Y MCY', days: 2, legal_state: 'FIRMA BANCO'},
          { credit_entity: 'DAVIVIENDA', subsidy_entity: 'SUBSIDIO CAJA Y MCY', days: 7, legal_state: 'PROTOCOLIZACION'},
          { credit_entity: 'DAVIVIENDA', subsidy_entity: 'SUBSIDIO CAJA Y MCY', days: 0, legal_state: 'LIQUIDACION'},
          { credit_entity: 'DAVIVIENDA', subsidy_entity: 'SUBSIDIO CAJA Y MCY', days: 3, legal_state: 'ENTRADA DE REGISTRO'},
          { credit_entity: 'DAVIVIENDA', subsidy_entity: 'SUBSIDIO CAJA Y MCY', days: 5, legal_state: 'RADICADO EN ESPERA DE DESEMBOLSO'},
          { credit_entity: 'DAVIVIENDA', subsidy_entity: 'SUBSIDIO CAJA Y MCY', days: 3, legal_state: 'ENTREGA DE VIVIENDA'},
          { credit_entity: 'DAVIVIENDA', subsidy_entity: 'SUBSIDIO CAJA Y MCY', days: 10, legal_state: 'ESCRITURA EN REGISTRO'},
          { credit_entity: 'DAVIVIENDA', subsidy_entity: 'SUBSIDIO CAJA Y MCY', days: 0, legal_state: 'ACLARATORIA AL SUBSIDIO'},
          { credit_entity: 'DAVIVIENDA', subsidy_entity: 'SUBSIDIO CAJA Y MCY', days: 19, legal_state: 'SUBSIDIO RADICADO'},
          { credit_entity: 'BANCOLOMBIA', subsidy_entity: 'SIN SUBSIDIO', days: 15, legal_state: 'PREAPROB Y CONSEC'},
          { credit_entity: 'BANCOLOMBIA', subsidy_entity: 'SIN SUBSIDIO', days: 15, legal_state: 'TRAMITE'},
          { credit_entity: 'BANCOLOMBIA', subsidy_entity: 'SIN SUBSIDIO', days: nil, legal_state: 'APROBADO'},
          { credit_entity: 'BANCOLOMBIA', subsidy_entity: 'SIN SUBSIDIO', days: 3, legal_state: 'AVALUO FINAL'},
          { credit_entity: 'BANCOLOMBIA', subsidy_entity: 'SIN SUBSIDIO', days: 10, legal_state: 'CARTA DE RATIFICACION '},
          { credit_entity: 'BANCOLOMBIA', subsidy_entity: 'SIN SUBSIDIO', days: 3, legal_state: 'ESTUDIO TITULOS'},
          { credit_entity: 'BANCOLOMBIA', subsidy_entity: 'SIN SUBSIDIO', days: 3, legal_state: 'ELAB ESCRITURACION'},
          { credit_entity: 'BANCOLOMBIA', subsidy_entity: 'SIN SUBSIDIO', days: 5, legal_state: 'REVISION FIDUCIA'},
          { credit_entity: 'BANCOLOMBIA', subsidy_entity: 'SIN SUBSIDIO', days: 5, legal_state: 'FIRMA ESC. CLIENTE'},
          { credit_entity: 'BANCOLOMBIA', subsidy_entity: 'SIN SUBSIDIO', days: 2, legal_state: 'NUMERACION ESCRITURA'},
          { credit_entity: 'BANCOLOMBIA', subsidy_entity: 'SIN SUBSIDIO', days: 1, legal_state: 'FIRMA ESC. CONSTRUCTORA'},
          { credit_entity: 'BANCOLOMBIA', subsidy_entity: 'SIN SUBSIDIO', days: 3, legal_state: 'FIRMA FIDUCIA'},
          { credit_entity: 'BANCOLOMBIA', subsidy_entity: 'SIN SUBSIDIO', days: 5, legal_state: 'FIRMA BANCO CONSTRUCTOR'},
          { credit_entity: 'BANCOLOMBIA', subsidy_entity: 'SIN SUBSIDIO', days: 3, legal_state: 'FIRMA BANCO'},
          { credit_entity: 'BANCOLOMBIA', subsidy_entity: 'SIN SUBSIDIO', days: 7, legal_state: 'PROTOCOLIZACION'},
          { credit_entity: 'BANCOLOMBIA', subsidy_entity: 'SIN SUBSIDIO', days: 0, legal_state: 'LIQUIDACION'},
          { credit_entity: 'BANCOLOMBIA', subsidy_entity: 'SIN SUBSIDIO', days: 3, legal_state: 'ENTRADA DE REGISTRO'},
          { credit_entity: 'BANCOLOMBIA', subsidy_entity: 'SIN SUBSIDIO', days: 5, legal_state: 'RADICADO EN ESPERA DE DESEMBOLSO'},
          { credit_entity: 'BANCOLOMBIA', subsidy_entity: 'SIN SUBSIDIO', days: 0, legal_state: 'ESCRITURA EN REGISTRO'},
          { credit_entity: 'BANCOLOMBIA', subsidy_entity: 'SIN SUBSIDIO', days: 3, legal_state: 'ENTREGA DE VIVIENDA'},
          { credit_entity: 'BANCOLOMBIA', subsidy_entity: 'SUBSIDIO CAJA', days: 15, legal_state: 'PREAPROB Y CONSEC'},
          { credit_entity: 'BANCOLOMBIA', subsidy_entity: 'SUBSIDIO CAJA', days: 15, legal_state: 'TRAMITE'},
          { credit_entity: 'BANCOLOMBIA', subsidy_entity: 'SUBSIDIO CAJA', days: nil, legal_state: 'APROBADO'},
          { credit_entity: 'BANCOLOMBIA', subsidy_entity: 'SUBSIDIO CAJA', days: 3, legal_state: 'AVALUO FINAL'},
          { credit_entity: 'BANCOLOMBIA', subsidy_entity: 'SUBSIDIO CAJA', days: 10, legal_state: 'CARTA DE RATIFICACION '},
          { credit_entity: 'BANCOLOMBIA', subsidy_entity: 'SUBSIDIO CAJA', days: 3, legal_state: 'ESTUDIO TITULOS'},
          { credit_entity: 'BANCOLOMBIA', subsidy_entity: 'SUBSIDIO CAJA', days: 3, legal_state: 'ELAB ESCRITURACION'},
          { credit_entity: 'BANCOLOMBIA', subsidy_entity: 'SUBSIDIO CAJA', days: 5, legal_state: 'REVISION FIDUCIA'},
          { credit_entity: 'BANCOLOMBIA', subsidy_entity: 'SUBSIDIO CAJA', days: 5, legal_state: 'FIRMA ESC. CLIENTE'},
          { credit_entity: 'BANCOLOMBIA', subsidy_entity: 'SUBSIDIO CAJA', days: 2, legal_state: 'NUMERACION ESCRITURA'},
          { credit_entity: 'BANCOLOMBIA', subsidy_entity: 'SUBSIDIO CAJA', days: 1, legal_state: 'FIRMA ESC. CONSTRUCTORA'},
          { credit_entity: 'BANCOLOMBIA', subsidy_entity: 'SUBSIDIO CAJA', days: 3, legal_state: 'FIRMA FIDUCIA'},
          { credit_entity: 'BANCOLOMBIA', subsidy_entity: 'SUBSIDIO CAJA', days: 5, legal_state: 'FIRMA BANCO CONSTRUCTOR'},
          { credit_entity: 'BANCOLOMBIA', subsidy_entity: 'SUBSIDIO CAJA', days: 3, legal_state: 'FIRMA BANCO'},
          { credit_entity: 'BANCOLOMBIA', subsidy_entity: 'SUBSIDIO CAJA', days: 7, legal_state: 'PROTOCOLIZACION'},
          { credit_entity: 'BANCOLOMBIA', subsidy_entity: 'SUBSIDIO CAJA', days: 0, legal_state: 'LIQUIDACION'},
          { credit_entity: 'BANCOLOMBIA', subsidy_entity: 'SUBSIDIO CAJA', days: 3, legal_state: 'ENTRADA DE REGISTRO'},
          { credit_entity: 'BANCOLOMBIA', subsidy_entity: 'SUBSIDIO CAJA', days: 5, legal_state: 'RADICADO EN ESPERA DE DESEMBOLSO'},
          { credit_entity: 'BANCOLOMBIA', subsidy_entity: 'SUBSIDIO CAJA', days: 3, legal_state: 'ENTREGA DE VIVIENDA'},
          { credit_entity: 'BANCOLOMBIA', subsidy_entity: 'SUBSIDIO CAJA', days: 10, legal_state: 'ESCRITURA EN REGISTRO'},
          { credit_entity: 'BANCOLOMBIA', subsidy_entity: 'SUBSIDIO CAJA', days: 0, legal_state: 'ACLARATORIA AL SUBSIDIO'},
          { credit_entity: 'BANCOLOMBIA', subsidy_entity: 'SUBSIDIO CAJA', days: 19, legal_state: 'SUBSIDIO RADICADO'},
          { credit_entity: 'BANCOLOMBIA', subsidy_entity: 'MCY', days: 15, legal_state: 'PREAPROB Y CONSEC'},
          { credit_entity: 'BANCOLOMBIA', subsidy_entity: 'MCY', days: 15, legal_state: 'TRAMITE'},
          { credit_entity: 'BANCOLOMBIA', subsidy_entity: 'MCY', days: nil, legal_state: 'APROBADO'},
          { credit_entity: 'BANCOLOMBIA', subsidy_entity: 'MCY', days: 3, legal_state: 'AVALUO FINAL'},
          { credit_entity: 'BANCOLOMBIA', subsidy_entity: 'MCY', days: 10, legal_state: 'CARTA DE RATIFICACION '},
          { credit_entity: 'BANCOLOMBIA', subsidy_entity: 'MCY', days: 15, legal_state: 'EN ESPERA DE RESOLUCION MCY (PROCESO 027)'},
          { credit_entity: 'BANCOLOMBIA', subsidy_entity: 'MCY', days: 3, legal_state: 'ESTUDIO TITULOS'},
          { credit_entity: 'BANCOLOMBIA', subsidy_entity: 'MCY', days: 3, legal_state: 'ELAB ESCRITURACION'},
          { credit_entity: 'BANCOLOMBIA', subsidy_entity: 'MCY', days: 5, legal_state: 'REVISION FIDUCIA'},
          { credit_entity: 'BANCOLOMBIA', subsidy_entity: 'MCY', days: 5, legal_state: 'FIRMA ESC. CLIENTE'},
          { credit_entity: 'BANCOLOMBIA', subsidy_entity: 'MCY', days: 2, legal_state: 'NUMERACION ESCRITURA'},
          { credit_entity: 'BANCOLOMBIA', subsidy_entity: 'MCY', days: 1, legal_state: 'FIRMA ESC. CONSTRUCTORA'},
          { credit_entity: 'BANCOLOMBIA', subsidy_entity: 'MCY', days: 3, legal_state: 'FIRMA FIDUCIA'},
          { credit_entity: 'BANCOLOMBIA', subsidy_entity: 'MCY', days: 5, legal_state: 'FIRMA BANCO CONSTRUCTOR'},
          { credit_entity: 'BANCOLOMBIA', subsidy_entity: 'MCY', days: 3, legal_state: 'FIRMA BANCO'},
          { credit_entity: 'BANCOLOMBIA', subsidy_entity: 'MCY', days: 7, legal_state: 'PROTOCOLIZACION'},
          { credit_entity: 'BANCOLOMBIA', subsidy_entity: 'MCY', days: 0, legal_state: 'LIQUIDACION'},
          { credit_entity: 'BANCOLOMBIA', subsidy_entity: 'MCY', days: 3, legal_state: 'ENTRADA DE REGISTRO'},
          { credit_entity: 'BANCOLOMBIA', subsidy_entity: 'MCY', days: 5, legal_state: 'RADICADO EN ESPERA DE DESEMBOLSO'},
          { credit_entity: 'BANCOLOMBIA', subsidy_entity: 'MCY', days: 28, legal_state: 'SUBSIDIO RADICADO'},
          { credit_entity: 'BANCOLOMBIA', subsidy_entity: 'MCY', days: 3, legal_state: 'ENTREGA DE VIVIENDA'},
          { credit_entity: 'BANCOLOMBIA', subsidy_entity: 'SUBSIDIO CAJA Y MCY', days: 15, legal_state: 'PREAPROB Y CONSEC'},
          { credit_entity: 'BANCOLOMBIA', subsidy_entity: 'SUBSIDIO CAJA Y MCY', days: 15, legal_state: 'TRAMITE'},
          { credit_entity: 'BANCOLOMBIA', subsidy_entity: 'SUBSIDIO CAJA Y MCY', days: nil, legal_state: 'APROBADO'},
          { credit_entity: 'BANCOLOMBIA', subsidy_entity: 'SUBSIDIO CAJA Y MCY', days: 3, legal_state: 'AVALUO FINAL'},
          { credit_entity: 'BANCOLOMBIA', subsidy_entity: 'SUBSIDIO CAJA Y MCY', days: 10, legal_state: 'CARTA DE RATIFICACION '},
          { credit_entity: 'BANCOLOMBIA', subsidy_entity: 'SUBSIDIO CAJA Y MCY', days: 15, legal_state: 'EN ESPERA DE RESOLUCION MCY (PROCESO 027)'},
          { credit_entity: 'BANCOLOMBIA', subsidy_entity: 'SUBSIDIO CAJA Y MCY', days: 3, legal_state: 'ESTUDIO TITULOS'},
          { credit_entity: 'BANCOLOMBIA', subsidy_entity: 'SUBSIDIO CAJA Y MCY', days: 3, legal_state: 'ELAB ESCRITURACION'},
          { credit_entity: 'BANCOLOMBIA', subsidy_entity: 'SUBSIDIO CAJA Y MCY', days: 5, legal_state: 'REVISION FIDUCIA'},
          { credit_entity: 'BANCOLOMBIA', subsidy_entity: 'SUBSIDIO CAJA Y MCY', days: 5, legal_state: 'FIRMA ESC. CLIENTE'},
          { credit_entity: 'BANCOLOMBIA', subsidy_entity: 'SUBSIDIO CAJA Y MCY', days: 2, legal_state: 'NUMERACION ESCRITURA'},
          { credit_entity: 'BANCOLOMBIA', subsidy_entity: 'SUBSIDIO CAJA Y MCY', days: 1, legal_state: 'FIRMA ESC. CONSTRUCTORA'},
          { credit_entity: 'BANCOLOMBIA', subsidy_entity: 'SUBSIDIO CAJA Y MCY', days: 3, legal_state: 'FIRMA FIDUCIA'},
          { credit_entity: 'BANCOLOMBIA', subsidy_entity: 'SUBSIDIO CAJA Y MCY', days: 5, legal_state: 'FIRMA BANCO CONSTRUCTOR'},
          { credit_entity: 'BANCOLOMBIA', subsidy_entity: 'SUBSIDIO CAJA Y MCY', days: 3, legal_state: 'FIRMA BANCO'},
          { credit_entity: 'BANCOLOMBIA', subsidy_entity: 'SUBSIDIO CAJA Y MCY', days: 7, legal_state: 'PROTOCOLIZACION'},
          { credit_entity: 'BANCOLOMBIA', subsidy_entity: 'SUBSIDIO CAJA Y MCY', days: 0, legal_state: 'LIQUIDACION'},
          { credit_entity: 'BANCOLOMBIA', subsidy_entity: 'SUBSIDIO CAJA Y MCY', days: 3, legal_state: 'ENTRADA DE REGISTRO'},
          { credit_entity: 'BANCOLOMBIA', subsidy_entity: 'SUBSIDIO CAJA Y MCY', days: 5, legal_state: 'RADICADO EN ESPERA DE DESEMBOLSO'},
          { credit_entity: 'BANCOLOMBIA', subsidy_entity: 'SUBSIDIO CAJA Y MCY', days: 3, legal_state: 'ENTREGA DE VIVIENDA'},
          { credit_entity: 'BANCOLOMBIA', subsidy_entity: 'SUBSIDIO CAJA Y MCY', days: 10, legal_state: 'ESCRITURA EN REGISTRO'},
          { credit_entity: 'BANCOLOMBIA', subsidy_entity: 'SUBSIDIO CAJA Y MCY', days: 0, legal_state: 'ACLARATORIA AL SUBSIDIO'},
          { credit_entity: 'BANCOLOMBIA', subsidy_entity: 'SUBSIDIO CAJA Y MCY', days: 19, legal_state: 'SUBSIDIO RADICADO'},
          { credit_entity: 'OTROS', subsidy_entity: 'SIN SUBSIDIO', days: 15, legal_state: 'PREAPROB Y CONSEC'},
          { credit_entity: 'OTROS', subsidy_entity: 'SIN SUBSIDIO', days: 15, legal_state: 'TRAMITE'},
          { credit_entity: 'OTROS', subsidy_entity: 'SIN SUBSIDIO', days: nil, legal_state: 'APROBADO'},
          { credit_entity: 'OTROS', subsidy_entity: 'SIN SUBSIDIO', days: 7, legal_state: 'AVALUO FINAL'},
          { credit_entity: 'OTROS', subsidy_entity: 'SIN SUBSIDIO', days: 8, legal_state: 'ESTUDIO TITULOS'},
          { credit_entity: 'OTROS', subsidy_entity: 'SIN SUBSIDIO', days: 0, legal_state: 'CARTA DE RATIFICACION '},
          { credit_entity: 'OTROS', subsidy_entity: 'SIN SUBSIDIO', days: 3, legal_state: 'ELAB ESCRITURACION'},
          { credit_entity: 'OTROS', subsidy_entity: 'SIN SUBSIDIO', days: 5, legal_state: 'REVISION FIDUCIA'},
          { credit_entity: 'OTROS', subsidy_entity: 'SIN SUBSIDIO', days: 5, legal_state: 'FIRMA ESC. CLIENTE'},
          { credit_entity: 'OTROS', subsidy_entity: 'SIN SUBSIDIO', days: 2, legal_state: 'NUMERACION ESCRITURA'},
          { credit_entity: 'OTROS', subsidy_entity: 'SIN SUBSIDIO', days: 1, legal_state: 'FIRMA ESC. CONSTRUCTORA'},
          { credit_entity: 'OTROS', subsidy_entity: 'SIN SUBSIDIO', days: 2, legal_state: 'FIRMA FIDUCIA'},
          { credit_entity: 'OTROS', subsidy_entity: 'SIN SUBSIDIO', days: 5, legal_state: 'FIRMA BANCO CONSTRUCTOR'},
          { credit_entity: 'OTROS', subsidy_entity: 'SIN SUBSIDIO', days: 5, legal_state: 'FIRMA BANCO'},
          { credit_entity: 'OTROS', subsidy_entity: 'SIN SUBSIDIO', days: 7, legal_state: 'PROTOCOLIZACION'},
          { credit_entity: 'OTROS', subsidy_entity: 'SIN SUBSIDIO', days: 0, legal_state: 'LIQUIDACION'},
          { credit_entity: 'OTROS', subsidy_entity: 'SIN SUBSIDIO', days: 3, legal_state: 'ENTRADA DE REGISTRO'},
          { credit_entity: 'OTROS', subsidy_entity: 'SIN SUBSIDIO', days: 10, legal_state: 'ESCRITURA EN REGISTRO'},
          { credit_entity: 'OTROS', subsidy_entity: 'SIN SUBSIDIO', days: 7, legal_state: 'RADICADO EN ESPERA DE DESEMBOLSO'},
          { credit_entity: 'OTROS', subsidy_entity: 'SIN SUBSIDIO', days: 3, legal_state: 'ENTREGA DE VIVIENDA'},
          { credit_entity: 'OTROS', subsidy_entity: 'SUBSIDIO CAJA', days: 15, legal_state: 'PREAPROB Y CONSEC'},
          { credit_entity: 'OTROS', subsidy_entity: 'SUBSIDIO CAJA', days: 15, legal_state: 'TRAMITE'},
          { credit_entity: 'OTROS', subsidy_entity: 'SUBSIDIO CAJA', days: nil, legal_state: 'APROBADO'},
          { credit_entity: 'OTROS', subsidy_entity: 'SUBSIDIO CAJA', days: 7, legal_state: 'AVALUO FINAL'},
          { credit_entity: 'OTROS', subsidy_entity: 'SUBSIDIO CAJA', days: 8, legal_state: 'ESTUDIO TITULOS'},
          { credit_entity: 'OTROS', subsidy_entity: 'SUBSIDIO CAJA', days: 0, legal_state: 'CARTA DE RATIFICACION '},
          { credit_entity: 'OTROS', subsidy_entity: 'SUBSIDIO CAJA', days: 3, legal_state: 'ELAB ESCRITURACION'},
          { credit_entity: 'OTROS', subsidy_entity: 'SUBSIDIO CAJA', days: 5, legal_state: 'REVISION FIDUCIA'},
          { credit_entity: 'OTROS', subsidy_entity: 'SUBSIDIO CAJA', days: 5, legal_state: 'FIRMA ESC. CLIENTE'},
          { credit_entity: 'OTROS', subsidy_entity: 'SUBSIDIO CAJA', days: 2, legal_state: 'NUMERACION ESCRITURA'},
          { credit_entity: 'OTROS', subsidy_entity: 'SUBSIDIO CAJA', days: 1, legal_state: 'FIRMA ESC. CONSTRUCTORA'},
          { credit_entity: 'OTROS', subsidy_entity: 'SUBSIDIO CAJA', days: 2, legal_state: 'FIRMA FIDUCIA'},
          { credit_entity: 'OTROS', subsidy_entity: 'SUBSIDIO CAJA', days: 5, legal_state: 'FIRMA BANCO CONSTRUCTOR'},
          { credit_entity: 'OTROS', subsidy_entity: 'SUBSIDIO CAJA', days: 5, legal_state: 'FIRMA BANCO'},
          { credit_entity: 'OTROS', subsidy_entity: 'SUBSIDIO CAJA', days: 7, legal_state: 'PROTOCOLIZACION'},
          { credit_entity: 'OTROS', subsidy_entity: 'SUBSIDIO CAJA', days: 0, legal_state: 'LIQUIDACION'},
          { credit_entity: 'OTROS', subsidy_entity: 'SUBSIDIO CAJA', days: 3, legal_state: 'ENTRADA DE REGISTRO'},
          { credit_entity: 'OTROS', subsidy_entity: 'SUBSIDIO CAJA', days: 10, legal_state: 'ESCRITURA EN REGISTRO'},
          { credit_entity: 'OTROS', subsidy_entity: 'SUBSIDIO CAJA', days: 7, legal_state: 'RADICADO EN ESPERA DE DESEMBOLSO'},
          { credit_entity: 'OTROS', subsidy_entity: 'SUBSIDIO CAJA', days: 0, legal_state: 'ACLARATORIA AL SUBSIDIO'},
          { credit_entity: 'OTROS', subsidy_entity: 'SUBSIDIO CAJA', days: 19, legal_state: 'SUBSIDIO RADICADO'},
          { credit_entity: 'OTROS', subsidy_entity: 'SUBSIDIO CAJA', days: 3, legal_state: 'ENTREGA DE VIVIENDA'},
          { credit_entity: 'OTROS', subsidy_entity: 'MCY', days: 15, legal_state: 'PREAPROB Y CONSEC'},
          { credit_entity: 'OTROS', subsidy_entity: 'MCY', days: 15, legal_state: 'TRAMITE'},
          { credit_entity: 'OTROS', subsidy_entity: 'MCY', days: nil, legal_state: 'APROBADO'},
          { credit_entity: 'OTROS', subsidy_entity: 'MCY', days: 7, legal_state: 'AVALUO FINAL'},
          { credit_entity: 'OTROS', subsidy_entity: 'MCY', days: 8, legal_state: 'ESTUDIO TITULOS'},
          { credit_entity: 'OTROS', subsidy_entity: 'MCY', days: 0, legal_state: 'CARTA DE RATIFICACION '},
          { credit_entity: 'OTROS', subsidy_entity: 'MCY', days: 15, legal_state: 'EN ESPERA DE RESOLUCION MCY (PROCESO 027)'},
          { credit_entity: 'OTROS', subsidy_entity: 'MCY', days: 3, legal_state: 'ELAB ESCRITURACION'},
          { credit_entity: 'OTROS', subsidy_entity: 'MCY', days: 5, legal_state: 'REVISION FIDUCIA'},
          { credit_entity: 'OTROS', subsidy_entity: 'MCY', days: 5, legal_state: 'FIRMA ESC. CLIENTE'},
          { credit_entity: 'OTROS', subsidy_entity: 'MCY', days: 2, legal_state: 'NUMERACION ESCRITURA'},
          { credit_entity: 'OTROS', subsidy_entity: 'MCY', days: 1, legal_state: 'FIRMA ESC. CONSTRUCTORA'},
          { credit_entity: 'OTROS', subsidy_entity: 'MCY', days: 2, legal_state: 'FIRMA FIDUCIA'},
          { credit_entity: 'OTROS', subsidy_entity: 'MCY', days: 5, legal_state: 'FIRMA BANCO CONSTRUCTOR'},
          { credit_entity: 'OTROS', subsidy_entity: 'MCY', days: 5, legal_state: 'FIRMA BANCO'},
          { credit_entity: 'OTROS', subsidy_entity: 'MCY', days: 7, legal_state: 'PROTOCOLIZACION'},
          { credit_entity: 'OTROS', subsidy_entity: 'MCY', days: 0, legal_state: 'LIQUIDACION'},
          { credit_entity: 'OTROS', subsidy_entity: 'MCY', days: 3, legal_state: 'ENTRADA DE REGISTRO'},
          { credit_entity: 'OTROS', subsidy_entity: 'MCY', days: 10, legal_state: 'ESCRITURA EN REGISTRO'},
          { credit_entity: 'OTROS', subsidy_entity: 'MCY', days: 7, legal_state: 'RADICADO EN ESPERA DE DESEMBOLSO'},
          { credit_entity: 'OTROS', subsidy_entity: 'MCY', days: 28, legal_state: 'SUBSIDIO RADICADO'},
          { credit_entity: 'OTROS', subsidy_entity: 'MCY', days: 3, legal_state: 'ENTREGA DE VIVIENDA'},
          { credit_entity: 'OTROS', subsidy_entity: 'SUBSIDIO CAJA Y MCY', days: 15, legal_state: 'PREAPROB Y CONSEC'},
          { credit_entity: 'OTROS', subsidy_entity: 'SUBSIDIO CAJA Y MCY', days: 15, legal_state: 'TRAMITE'},
          { credit_entity: 'OTROS', subsidy_entity: 'SUBSIDIO CAJA Y MCY', days: nil, legal_state: 'APROBADO'},
          { credit_entity: 'OTROS', subsidy_entity: 'SUBSIDIO CAJA Y MCY', days: 7, legal_state: 'AVALUO FINAL'},
          { credit_entity: 'OTROS', subsidy_entity: 'SUBSIDIO CAJA Y MCY', days: 8, legal_state: 'ESTUDIO TITULOS'},
          { credit_entity: 'OTROS', subsidy_entity: 'SUBSIDIO CAJA Y MCY', days: 0, legal_state: 'CARTA DE RATIFICACION '},
          { credit_entity: 'OTROS', subsidy_entity: 'SUBSIDIO CAJA Y MCY', days: 15, legal_state: 'EN ESPERA DE RESOLUCION MCY (PROCESO 027)'},
          { credit_entity: 'OTROS', subsidy_entity: 'SUBSIDIO CAJA Y MCY', days: 3, legal_state: 'ELAB ESCRITURACION'},
          { credit_entity: 'OTROS', subsidy_entity: 'SUBSIDIO CAJA Y MCY', days: 5, legal_state: 'REVISION FIDUCIA'},
          { credit_entity: 'OTROS', subsidy_entity: 'SUBSIDIO CAJA Y MCY', days: 5, legal_state: 'FIRMA ESC. CLIENTE'},
          { credit_entity: 'OTROS', subsidy_entity: 'SUBSIDIO CAJA Y MCY', days: 2, legal_state: 'NUMERACION ESCRITURA'},
          { credit_entity: 'OTROS', subsidy_entity: 'SUBSIDIO CAJA Y MCY', days: 1, legal_state: 'FIRMA ESC. CONSTRUCTORA'},
          { credit_entity: 'OTROS', subsidy_entity: 'SUBSIDIO CAJA Y MCY', days: 2, legal_state: 'FIRMA FIDUCIA'},
          { credit_entity: 'OTROS', subsidy_entity: 'SUBSIDIO CAJA Y MCY', days: 5, legal_state: 'FIRMA BANCO CONSTRUCTOR'},
          { credit_entity: 'OTROS', subsidy_entity: 'SUBSIDIO CAJA Y MCY', days: 5, legal_state: 'FIRMA BANCO'},
          { credit_entity: 'OTROS', subsidy_entity: 'SUBSIDIO CAJA Y MCY', days: 7, legal_state: 'PROTOCOLIZACION'},
          { credit_entity: 'OTROS', subsidy_entity: 'SUBSIDIO CAJA Y MCY', days: 0, legal_state: 'LIQUIDACION'},
          { credit_entity: 'OTROS', subsidy_entity: 'SUBSIDIO CAJA Y MCY', days: 3, legal_state: 'ENTRADA DE REGISTRO'},
          { credit_entity: 'OTROS', subsidy_entity: 'SUBSIDIO CAJA Y MCY', days: 10, legal_state: 'ESCRITURA EN REGISTRO'},
          { credit_entity: 'OTROS', subsidy_entity: 'SUBSIDIO CAJA Y MCY', days: 7, legal_state: 'RADICADO EN ESPERA DE DESEMBOLSO'},
          { credit_entity: 'OTROS', subsidy_entity: 'SUBSIDIO CAJA Y MCY', days: 0, legal_state: 'ACLARATORIA AL SUBSIDIO'},
          { credit_entity: 'OTROS', subsidy_entity: 'SUBSIDIO CAJA Y MCY', days: 19, legal_state: 'SUBSIDIO RADICADO'},
          { credit_entity: 'OTROS', subsidy_entity: 'SUBSIDIO CAJA Y MCY', days: 3, legal_state: 'ENTREGA DE VIVIENDA'},
          { credit_entity: 'F.N.A.', subsidy_entity: 'SIN SUBSIDIO', days: 15, legal_state: 'PREAPROB Y CONSEC'},
          { credit_entity: 'F.N.A.', subsidy_entity: 'SIN SUBSIDIO', days: 15, legal_state: 'TRAMITE'},
          { credit_entity: 'F.N.A.', subsidy_entity: 'SIN SUBSIDIO', days: nil, legal_state: 'APROBADO'},
          { credit_entity: 'F.N.A.', subsidy_entity: 'SIN SUBSIDIO', days: 30, legal_state: 'AVALUO FINAL'},
          { credit_entity: 'F.N.A.', subsidy_entity: 'SIN SUBSIDIO', days: 20, legal_state: 'ESTUDIO TITULOS'},
          { credit_entity: 'F.N.A.', subsidy_entity: 'SIN SUBSIDIO', days: 3, legal_state: 'ELAB ESCRITURACION'},
          { credit_entity: 'F.N.A.', subsidy_entity: 'SIN SUBSIDIO', days: 5, legal_state: 'REVISION FIDUCIA'},
          { credit_entity: 'F.N.A.', subsidy_entity: 'SIN SUBSIDIO', days: 5, legal_state: 'FIRMA ESC. CLIENTE'},
          { credit_entity: 'F.N.A.', subsidy_entity: 'SIN SUBSIDIO', days: 2, legal_state: 'NUMERACION ESCRITURA'},
          { credit_entity: 'F.N.A.', subsidy_entity: 'SIN SUBSIDIO', days: 1, legal_state: 'FIRMA ESC. CONSTRUCTORA'},
          { credit_entity: 'F.N.A.', subsidy_entity: 'SIN SUBSIDIO', days: 2, legal_state: 'FIRMA FIDUCIA'},
          { credit_entity: 'F.N.A.', subsidy_entity: 'SIN SUBSIDIO', days: 2, legal_state: 'FIRMA BANCO CONSTRUCTOR'},
          { credit_entity: 'F.N.A.', subsidy_entity: 'SIN SUBSIDIO', days: 7, legal_state: 'FIRMA BANCO'},
          { credit_entity: 'F.N.A.', subsidy_entity: 'SIN SUBSIDIO', days: 7, legal_state: 'PROTOCOLIZACION'},
          { credit_entity: 'F.N.A.', subsidy_entity: 'SIN SUBSIDIO', days: 0, legal_state: 'LIQUIDACION'},
          { credit_entity: 'F.N.A.', subsidy_entity: 'SIN SUBSIDIO', days: 3, legal_state: 'ENTRADA DE REGISTRO'},
          { credit_entity: 'F.N.A.', subsidy_entity: 'SIN SUBSIDIO', days: 10, legal_state: 'ESCRITURA EN REGISTRO'},
          { credit_entity: 'F.N.A.', subsidy_entity: 'SIN SUBSIDIO', days: 8, legal_state: 'RADICADO EN ESPERA DE DESEMBOLSO'},
          { credit_entity: 'F.N.A.', subsidy_entity: 'SIN SUBSIDIO', days: 3, legal_state: 'ENTREGA DE VIVIENDA'},
          { credit_entity: 'F.N.A.', subsidy_entity: 'SUBSIDIO CAJA', days: 15, legal_state: 'PREAPROB Y CONSEC'},
          { credit_entity: 'F.N.A.', subsidy_entity: 'SUBSIDIO CAJA', days: 15, legal_state: 'TRAMITE'},
          { credit_entity: 'F.N.A.', subsidy_entity: 'SUBSIDIO CAJA', days: nil, legal_state: 'APROBADO'},
          { credit_entity: 'F.N.A.', subsidy_entity: 'SUBSIDIO CAJA', days: 30, legal_state: 'AVALUO FINAL'},
          { credit_entity: 'F.N.A.', subsidy_entity: 'SUBSIDIO CAJA', days: 20, legal_state: 'ESTUDIO TITULOS'},
          { credit_entity: 'F.N.A.', subsidy_entity: 'SUBSIDIO CAJA', days: 3, legal_state: 'ELAB ESCRITURACION'},
          { credit_entity: 'F.N.A.', subsidy_entity: 'SUBSIDIO CAJA', days: 5, legal_state: 'REVISION FIDUCIA'},
          { credit_entity: 'F.N.A.', subsidy_entity: 'SUBSIDIO CAJA', days: 5, legal_state: 'FIRMA ESC. CLIENTE'},
          { credit_entity: 'F.N.A.', subsidy_entity: 'SUBSIDIO CAJA', days: 2, legal_state: 'NUMERACION ESCRITURA'},
          { credit_entity: 'F.N.A.', subsidy_entity: 'SUBSIDIO CAJA', days: 1, legal_state: 'FIRMA ESC. CONSTRUCTORA'},
          { credit_entity: 'F.N.A.', subsidy_entity: 'SUBSIDIO CAJA', days: 2, legal_state: 'FIRMA FIDUCIA'},
          { credit_entity: 'F.N.A.', subsidy_entity: 'SUBSIDIO CAJA', days: 2, legal_state: 'FIRMA BANCO CONSTRUCTOR'},
          { credit_entity: 'F.N.A.', subsidy_entity: 'SUBSIDIO CAJA', days: 7, legal_state: 'FIRMA BANCO'},
          { credit_entity: 'F.N.A.', subsidy_entity: 'SUBSIDIO CAJA', days: 7, legal_state: 'PROTOCOLIZACION'},
          { credit_entity: 'F.N.A.', subsidy_entity: 'SUBSIDIO CAJA', days: 0, legal_state: 'LIQUIDACION'},
          { credit_entity: 'F.N.A.', subsidy_entity: 'SUBSIDIO CAJA', days: 3, legal_state: 'ENTRADA DE REGISTRO'},
          { credit_entity: 'F.N.A.', subsidy_entity: 'SUBSIDIO CAJA', days: 10, legal_state: 'ESCRITURA EN REGISTRO'},
          { credit_entity: 'F.N.A.', subsidy_entity: 'SUBSIDIO CAJA', days: 8, legal_state: 'RADICADO EN ESPERA DE DESEMBOLSO'},
          { credit_entity: 'F.N.A.', subsidy_entity: 'SUBSIDIO CAJA', days: 0, legal_state: 'ACLARATORIA AL SUBSIDIO'},
          { credit_entity: 'F.N.A.', subsidy_entity: 'SUBSIDIO CAJA', days: 19, legal_state: 'SUBSIDIO RADICADO'},
          { credit_entity: 'F.N.A.', subsidy_entity: 'SUBSIDIO CAJA', days: 3, legal_state: 'ENTREGA DE VIVIENDA'},
          { credit_entity: 'F.N.A.', subsidy_entity: 'MCY', days: 15, legal_state: 'PREAPROB Y CONSEC'},
          { credit_entity: 'F.N.A.', subsidy_entity: 'MCY', days: 15, legal_state: 'TRAMITE'},
          { credit_entity: 'F.N.A.', subsidy_entity: 'MCY', days: nil, legal_state: 'APROBADO'},
          { credit_entity: 'F.N.A.', subsidy_entity: 'MCY', days: 30, legal_state: 'AVALUO FINAL'},
          { credit_entity: 'F.N.A.', subsidy_entity: 'MCY', days: 20, legal_state: 'ESTUDIO TITULOS'},
          { credit_entity: 'F.N.A.', subsidy_entity: 'MCY', days: 15, legal_state: 'EN ESPERA DE RESOLUCION MCY (PROCESO 027)'},
          { credit_entity: 'F.N.A.', subsidy_entity: 'MCY', days: 3, legal_state: 'ELAB ESCRITURACION'},
          { credit_entity: 'F.N.A.', subsidy_entity: 'MCY', days: 5, legal_state: 'REVISION FIDUCIA'},
          { credit_entity: 'F.N.A.', subsidy_entity: 'MCY', days: 5, legal_state: 'FIRMA ESC. CLIENTE'},
          { credit_entity: 'F.N.A.', subsidy_entity: 'MCY', days: 2, legal_state: 'NUMERACION ESCRITURA'},
          { credit_entity: 'F.N.A.', subsidy_entity: 'MCY', days: 1, legal_state: 'FIRMA ESC. CONSTRUCTORA'},
          { credit_entity: 'F.N.A.', subsidy_entity: 'MCY', days: 2, legal_state: 'FIRMA FIDUCIA'},
          { credit_entity: 'F.N.A.', subsidy_entity: 'MCY', days: 2, legal_state: 'FIRMA BANCO CONSTRUCTOR'},
          { credit_entity: 'F.N.A.', subsidy_entity: 'MCY', days: 7, legal_state: 'FIRMA BANCO'},
          { credit_entity: 'F.N.A.', subsidy_entity: 'MCY', days: 7, legal_state: 'PROTOCOLIZACION'},
          { credit_entity: 'F.N.A.', subsidy_entity: 'MCY', days: 0, legal_state: 'LIQUIDACION'},
          { credit_entity: 'F.N.A.', subsidy_entity: 'MCY', days: 3, legal_state: 'ENTRADA DE REGISTRO'},
          { credit_entity: 'F.N.A.', subsidy_entity: 'MCY', days: 10, legal_state: 'ESCRITURA EN REGISTRO'},
          { credit_entity: 'F.N.A.', subsidy_entity: 'MCY', days: 8, legal_state: 'RADICADO EN ESPERA DE DESEMBOLSO'},
          { credit_entity: 'F.N.A.', subsidy_entity: 'MCY', days: 28, legal_state: 'SUBSIDIO RADICADO'},
          { credit_entity: 'F.N.A.', subsidy_entity: 'MCY', days: 3, legal_state: 'ENTREGA DE VIVIENDA'},
          { credit_entity: 'F.N.A.', subsidy_entity: 'SUBSIDIO CAJA Y MCY', days: 15, legal_state: 'PREAPROB Y CONSEC'},
          { credit_entity: 'F.N.A.', subsidy_entity: 'SUBSIDIO CAJA Y MCY', days: 15, legal_state: 'TRAMITE'},
          { credit_entity: 'F.N.A.', subsidy_entity: 'SUBSIDIO CAJA Y MCY', days: nil, legal_state: 'APROBADO'},
          { credit_entity: 'F.N.A.', subsidy_entity: 'SUBSIDIO CAJA Y MCY', days: 30, legal_state: 'AVALUO FINAL'},
          { credit_entity: 'F.N.A.', subsidy_entity: 'SUBSIDIO CAJA Y MCY', days: 20, legal_state: 'ESTUDIO TITULOS'},
          { credit_entity: 'F.N.A.', subsidy_entity: 'SUBSIDIO CAJA Y MCY', days: 15, legal_state: 'EN ESPERA DE RESOLUCION MCY (PROCESO 027)'},
          { credit_entity: 'F.N.A.', subsidy_entity: 'SUBSIDIO CAJA Y MCY', days: 3, legal_state: 'ELAB ESCRITURACION' },
          { credit_entity: 'F.N.A.', subsidy_entity: 'SUBSIDIO CAJA Y MCY', days: 5, legal_state: 'REVISION FIDUCIA'},
          { credit_entity: 'F.N.A.', subsidy_entity: 'SUBSIDIO CAJA Y MCY', days: 5, legal_state: 'FIRMA ESC. CLIENTE'},
          { credit_entity: 'F.N.A.', subsidy_entity: 'SUBSIDIO CAJA Y MCY', days: 2, legal_state: 'NUMERACION ESCRITURA'},
          { credit_entity: 'F.N.A.', subsidy_entity: 'SUBSIDIO CAJA Y MCY', days: 1, legal_state: 'FIRMA ESC. CONSTRUCTORA'},
          { credit_entity: 'F.N.A.', subsidy_entity: 'SUBSIDIO CAJA Y MCY', days: 2, legal_state: 'FIRMA FIDUCIA'},
          { credit_entity: 'F.N.A.', subsidy_entity: 'SUBSIDIO CAJA Y MCY', days: 2, legal_state: 'FIRMA BANCO CONSTRUCTOR'},
          { credit_entity: 'F.N.A.', subsidy_entity: 'SUBSIDIO CAJA Y MCY', days: 7, legal_state: 'FIRMA BANCO'},
          { credit_entity: 'F.N.A.', subsidy_entity: 'SUBSIDIO CAJA Y MCY', days: 7, legal_state: 'PROTOCOLIZACION'},
          { credit_entity: 'F.N.A.', subsidy_entity: 'SUBSIDIO CAJA Y MCY', days: 0, legal_state: 'LIQUIDACION'},
          { credit_entity: 'F.N.A.', subsidy_entity: 'SUBSIDIO CAJA Y MCY', days: 3, legal_state: 'ENTRADA DE REGISTRO'},
          { credit_entity: 'F.N.A.', subsidy_entity: 'SUBSIDIO CAJA Y MCY', days: 10, legal_state: 'ESCRITURA EN REGISTRO'},
          { credit_entity: 'F.N.A.', subsidy_entity: 'SUBSIDIO CAJA Y MCY', days: 8, legal_state: 'RADICADO EN ESPERA DE DESEMBOLSO'},
          { credit_entity: 'F.N.A.', subsidy_entity: 'SUBSIDIO CAJA Y MCY', days: 0, legal_state: 'ACLARATORIA AL SUBSIDIO'},
          { credit_entity: 'F.N.A.', subsidy_entity: 'SUBSIDIO CAJA Y MCY', days: 19, legal_state: 'SUBSIDIO RADICADO'},
          { credit_entity: 'F.N.A.', subsidy_entity: 'SUBSIDIO CAJA Y MCY', days: 3, legal_state: 'ENTREGA DE VIVIENDA'},
          { credit_entity: 'VENTA DIRECTA', subsidy_entity: 'SUBSIDIO CAJA', days: 3, legal_state: 'ELAB ESCRITURACION'},
          { credit_entity: 'VENTA DIRECTA', subsidy_entity: 'SUBSIDIO CAJA', days: 5, legal_state: 'REVISION FIDUCIA'},
          { credit_entity: 'VENTA DIRECTA', subsidy_entity: 'SUBSIDIO CAJA', days: 5, legal_state: 'FIRMA ESC. CLIENTE'},
          { credit_entity: 'VENTA DIRECTA', subsidy_entity: 'SUBSIDIO CAJA', days: 2, legal_state: 'NUMERACION ESCRITURA'},
          { credit_entity: 'VENTA DIRECTA', subsidy_entity: 'SUBSIDIO CAJA', days: 1, legal_state: 'FIRMA ESC. CONSTRUCTORA'},
          { credit_entity: 'VENTA DIRECTA', subsidy_entity: 'SUBSIDIO CAJA', days: 2, legal_state: 'FIRMA FIDUCIA'},
          { credit_entity: 'VENTA DIRECTA', subsidy_entity: 'SUBSIDIO CAJA', days: 15, legal_state: 'FIRMA BANCO CONSTRUCTOR'},
          { credit_entity: 'VENTA DIRECTA', subsidy_entity: 'SUBSIDIO CAJA', days: 7, legal_state: 'PROTOCOLIZACION'},
          { credit_entity: 'VENTA DIRECTA', subsidy_entity: 'SUBSIDIO CAJA', days: 0, legal_state: 'LIQUIDACION'},
          { credit_entity: 'VENTA DIRECTA', subsidy_entity: 'SUBSIDIO CAJA', days: 3, legal_state: 'ENTRADA DE REGISTRO'},
          { credit_entity: 'VENTA DIRECTA', subsidy_entity: 'SUBSIDIO CAJA', days: 10, legal_state: 'ESCRITURA EN REGISTRO'},
          { credit_entity: 'VENTA DIRECTA', subsidy_entity: 'SUBSIDIO CAJA', days: 0, legal_state: 'ACLARATORIA AL SUBSIDIO'},
          { credit_entity: 'VENTA DIRECTA', subsidy_entity: 'SUBSIDIO CAJA', days: 19, legal_state: 'SUBSIDIO RADICADO'},
          { credit_entity: 'VENTA DIRECTA', subsidy_entity: 'SUBSIDIO CAJA', days: 3, legal_state: 'ENTREGA DE VIVIENDA'},
          { credit_entity: 'VENTA DIRECTA', subsidy_entity: 'SIN SUBSIDIO', days: 3, legal_state: 'ELAB ESCRITURACION'},
          { credit_entity: 'VENTA DIRECTA', subsidy_entity: 'SIN SUBSIDIO', days: 5, legal_state: 'REVISION FIDUCIA'},
          { credit_entity: 'VENTA DIRECTA', subsidy_entity: 'SIN SUBSIDIO', days: 5, legal_state: 'FIRMA ESC. CLIENTE'},
          { credit_entity: 'VENTA DIRECTA', subsidy_entity: 'SIN SUBSIDIO', days: 2, legal_state: 'NUMERACION ESCRITURA'},
          { credit_entity: 'VENTA DIRECTA', subsidy_entity: 'SIN SUBSIDIO', days: 1, legal_state: 'FIRMA ESC. CONSTRUCTORA'},
          { credit_entity: 'VENTA DIRECTA', subsidy_entity: 'SIN SUBSIDIO', days: 0, legal_state: 'FIRMA FIDUCIA'},
          { credit_entity: 'VENTA DIRECTA', subsidy_entity: 'SIN SUBSIDIO', days: 15, legal_state: 'FIRMA BANCO CONSTRUCTOR'},
          { credit_entity: 'VENTA DIRECTA', subsidy_entity: 'SIN SUBSIDIO', days: 7, legal_state: 'PROTOCOLIZACION'},
          { credit_entity: 'VENTA DIRECTA', subsidy_entity: 'SIN SUBSIDIO', days: 0, legal_state: 'LIQUIDACION'},
          { credit_entity: 'VENTA DIRECTA', subsidy_entity: 'SIN SUBSIDIO', days: 3, legal_state: 'ENTRADA DE REGISTRO'},
          { credit_entity: 'VENTA DIRECTA', subsidy_entity: 'SIN SUBSIDIO', days: 10, legal_state: 'ESCRITURA EN REGISTRO'},
          { credit_entity: 'VENTA DIRECTA', subsidy_entity: 'SIN SUBSIDIO', days: 3, legal_state: 'ENTREGA DE VIVIENDA' },
        ]
