# { name: 'DAVIVIENDA - SIN SUBSIDIO' days: 15, legal_state: 'PREAPROB Y CONSEC' },
# { name: 'DAVIVIENDA - SIN SUBSIDIO' days: , legal_state: 'APROBADO ' },
# { name: 'DAVIVIENDA - SIN SUBSIDIO' days: 8, legal_state: 'CARTA DE NOVEDAD' },
# { name: 'DAVIVIENDA - SIN SUBSIDIO' days: , legal_state: 'AVALUO PRELIMINAR' },
# { name: 'DAVIVIENDA - SIN SUBSIDIO' days: 3, legal_state: 'AVALUO FINAL' },
# { name: 'DAVIVIENDA - SIN SUBSIDIO' days: 1, legal_state: 'ELAB ESCRITURACION' },
# { name: 'DAVIVIENDA - SIN SUBSIDIO' days: 5, legal_state: 'REVISION FIDUCIA' },
# { name: 'DAVIVIENDA - SIN SUBSIDIO' days: 5, legal_state: 'FIRMA ESC. CLIENTE' },
# { name: 'DAVIVIENDA - SIN SUBSIDIO' days: , legal_state: 'NUMERACION ESCRITURA' },
# { name: 'DAVIVIENDA - SIN SUBSIDIO' days: 3, legal_state: 'ESTUDIO TITULO (PROCESO 027)' },
# { name: 'DAVIVIENDA - SIN SUBSIDIO' days: 2, legal_state: 'FIRMA FIDUCIA' },
# { name: 'DAVIVIENDA - SIN SUBSIDIO' days: 2, legal_state: 'FIRMA BANCO' },
# { name: 'DAVIVIENDA - SIN SUBSIDIO' days: 5, legal_state: 'PROTOCOLIZACION' },
# { name: 'DAVIVIENDA - SIN SUBSIDIO' days: , legal_state: 'LIQUIDACION' },
# { name: 'DAVIVIENDA - SIN SUBSIDIO' days: 3, legal_state: 'ENTRADA DE REGISTRO' },
# { name: 'DAVIVIENDA - SIN SUBSIDIO' days: 5, legal_state: 'RADICADO EN ESPERA DE DESEMBOLSO' },
# { name: 'DAVIVIENDA - SIN SUBSIDIO' days: 3, legal_state: 'ENTREGA DE VIVIENDA' },
# { name: 'DAVIVIENDA - SUBSIDIO CAJA' days: 15, legal_state: 'PREAPROB Y CONSEC' },
# { name: 'DAVIVIENDA - SUBSIDIO CAJA' days: , legal_state: 'APROBADO ' },
# { name: 'DAVIVIENDA - SUBSIDIO CAJA' days: 8, legal_state: 'CARTA DE NOVEDAD' },
# { name: 'DAVIVIENDA - SUBSIDIO CAJA' days: , legal_state: 'AVALUO PRELIMINAR' },
# { name: 'DAVIVIENDA - SUBSIDIO CAJA' days: 3, legal_state: 'AVALUO FINAL' },
# { name: 'DAVIVIENDA - SUBSIDIO CAJA' days: 1, legal_state: 'ELAB ESCRITURACION' },
# { name: 'DAVIVIENDA - SUBSIDIO CAJA' days: 5, legal_state: 'REVISION FIDUCIA' },
# { name: 'DAVIVIENDA - SUBSIDIO CAJA' days: 5, legal_state: 'FIRMA ESC. CLIENTE' },
# { name: 'DAVIVIENDA - SUBSIDIO CAJA' days: , legal_state: 'NUMERACION ESCRITURA' },
# { name: 'DAVIVIENDA - SUBSIDIO CAJA' days: 1, legal_state: 'FIRMA ESC. CONSTRUCTORA' },
# { name: 'DAVIVIENDA - SUBSIDIO CAJA' days: 3, legal_state: 'ESTUDIO TITULO (PROCESO 027)' },
# { name: 'DAVIVIENDA - SUBSIDIO CAJA' days: 2, legal_state: 'FIRMA FIDUCIA' },
# { name: 'DAVIVIENDA - SUBSIDIO CAJA' days: 2, legal_state: 'FIRMA BANCO' },
# { name: 'DAVIVIENDA - SUBSIDIO CAJA' days: 5, legal_state: 'PROTOCOLIZACION' },
# { name: 'DAVIVIENDA - SUBSIDIO CAJA' days: , legal_state: 'LIQUIDACION' },
# { name: 'DAVIVIENDA - SUBSIDIO CAJA' days: 3, legal_state: 'ENTRADA DE REGISTRO' },
# { name: 'DAVIVIENDA - SUBSIDIO CAJA' days: 5, legal_state: 'RADICADO EN ESPERA DE DESEMBOLSO' },
# { name: 'DAVIVIENDA - SUBSIDIO CAJA' days: 3, legal_state: 'ENTREGA DE VIVIENDA' },
# { name: 'DAVIVIENDA - SUBSIDIO CAJA' days: 10, legal_state: 'SALIDA DE REGISTRO' },
# { name: 'DAVIVIENDA - SUBSIDIO CAJA' days: , legal_state: 'ACLARATORIA AL SUBSIDIO' },
# { name: 'DAVIVIENDA - SUBSIDIO CAJA' days: 19, legal_state: 'SUBSIDIO RADICADO' },
# { name: 'DAVIVIENDA - MCY' days: 15, legal_state: 'PREAPROB Y CONSEC' },
# { name: 'DAVIVIENDA - MCY' days: , legal_state: 'APROBADO ' },
# { name: 'DAVIVIENDA - MCY' days: 8, legal_state: 'CARTA DE NOVEDAD' },
# { name: 'DAVIVIENDA - MCY' days: , legal_state: 'AVALUO PRELIMINAR' },
# { name: 'DAVIVIENDA - MCY' days: 3, legal_state: 'AVALUO FINAL' },
# { name: 'DAVIVIENDA - MCY' days: 18, legal_state: 'EN ESPERA DE RESOLUCION MCY (PROCESO 027)' },
# { name: 'DAVIVIENDA - MCY' days: 1, legal_state: 'ELAB ESCRITURACION' },
# { name: 'DAVIVIENDA - MCY' days: 5, legal_state: 'REVISION FIDUCIA' },
# { name: 'DAVIVIENDA - MCY' days: 5, legal_state: 'FIRMA ESC. CLIENTE' },
# { name: 'DAVIVIENDA - MCY' days: , legal_state: 'NUMERACION ESCRITURA' },
# { name: 'DAVIVIENDA - MCY' days: 1, legal_state: 'FIRMA ESC. CONSTRUCTORA' },
# { name: 'DAVIVIENDA - MCY' days: 3, legal_state: 'ESTUDIO TITULO (PROCESO 027)' },
# { name: 'DAVIVIENDA - MCY' days: 2, legal_state: 'FIRMA FIDUCIA' },
# { name: 'DAVIVIENDA - MCY' days: 2, legal_state: 'FIRMA BANCO' },
# { name: 'DAVIVIENDA - MCY' days: 5, legal_state: 'PROTOCOLIZACION' },
# { name: 'DAVIVIENDA - MCY' days: , legal_state: 'LIQUIDACION' },
# { name: 'DAVIVIENDA - MCY' days: 3, legal_state: 'ENTRADA DE REGISTRO' },
# { name: 'DAVIVIENDA - MCY' days: 5, legal_state: 'RADICADO EN ESPERA DE DESEMBOLSO' },
# { name: 'DAVIVIENDA - MCY' days: , legal_state: 'SALIDA DE REGISTRO' },
# { name: 'DAVIVIENDA - MCY' days: 28, legal_state: 'SUBSIDIO RADICADO' },
# { name: 'DAVIVIENDA - MCY' days: 3, legal_state: 'ENTREGA DE VIVIENDA' },
# { name: 'DAVIVIENDA - SUBSIDIO CAJA Y MCY' days: 15, legal_state: 'PREAPROB Y CONSEC' },
# { name: 'DAVIVIENDA - SUBSIDIO CAJA Y MCY' days: , legal_state: 'APROBADO ' },
# { name: 'DAVIVIENDA - SUBSIDIO CAJA Y MCY' days: 8, legal_state: 'CARTA DE NOVEDAD' },
# { name: 'DAVIVIENDA - SUBSIDIO CAJA Y MCY' days: , legal_state: 'AVALUO PRELIMINAR' },
# { name: 'DAVIVIENDA - SUBSIDIO CAJA Y MCY' days: 3, legal_state: 'AVALUO FINAL' },
# { name: 'DAVIVIENDA - SUBSIDIO CAJA Y MCY' days: 18, legal_state: 'EN ESPERA DE RESOLUCION MCY (PROCESO 027)' },
# { name: 'DAVIVIENDA - SUBSIDIO CAJA Y MCY' days: 1, legal_state: 'ELAB ESCRITURACION' },
# { name: 'DAVIVIENDA - SUBSIDIO CAJA Y MCY' days: 5, legal_state: 'REVISION FIDUCIA' },
# { name: 'DAVIVIENDA - SUBSIDIO CAJA Y MCY' days: 5, legal_state: 'FIRMA ESC. CLIENTE' },
# { name: 'DAVIVIENDA - SUBSIDIO CAJA Y MCY' days: , legal_state: 'NUMERACION ESCRITURA' },
# { name: 'DAVIVIENDA - SUBSIDIO CAJA Y MCY' days: 1, legal_state: 'FIRMA ESC. CONSTRUCTORA' },
# { name: 'DAVIVIENDA - SUBSIDIO CAJA Y MCY' days: 3, legal_state: 'ESTUDIO TITULO (PROCESO 027)' },
# { name: 'DAVIVIENDA - SUBSIDIO CAJA Y MCY' days: 2, legal_state: 'FIRMA FIDUCIA' },
# { name: 'DAVIVIENDA - SUBSIDIO CAJA Y MCY' days: 2, legal_state: 'FIRMA BANCO' },
# { name: 'DAVIVIENDA - SUBSDIO CAJA Y MCY' days: 5, legal_state: 'PROTOCOLIZACION' },
# { name: 'DAVIVIENDA - SUBSDIO CAJA Y MCY' days: , legal_state: 'LIQUIDACION' },
# { name: 'DAVIVIENDA - SUBSDIO CAJA Y MCY' days: 3, legal_state: 'ENTRADA DE REGISTRO' },
# { name: 'DAVIVIENDA - SUBSIDIO CAJA Y MCY' days: 5, legal_state: 'RADICADO EN ESPERA DE DESEMBOLSO' },
# { name: 'DAVIVIENDA - SUBSIDIO CAJA Y MCY' days: 3, legal_state: 'ENTREGA DE VIVIENDA' },
# { name: 'DAVIVIENDA - SUBSIDIO CAJA Y MCY' days: 10, legal_state: 'SALIDA DE REGISTRO' },
# { name: 'DAVIVIENDA - SUBSIDIO CAJA Y MCY' days: , legal_state: 'ACLARATORIA AL SUBSIDIO' },
# { name: 'DAVIVIENDA - SUBSIDIO CAJA Y MCY' days: 19, legal_state: 'SUBSIDIO RADICADO' },
# { name: 'BANCOLOMBIA - SIN SUBSIDIO' days: 15, legal_state: 'PREAPROB Y CONSEC' },
# { name: 'BANCOLOMBIA - SIN SUBSIDIO' days: , legal_state: 'APROBADO ' },
# { name: 'BANCOLOMBIA - SIN SUBSIDIO' days: 3, legal_state: 'AVALUO FINAL' },
# { name: 'BANCOLOMBIA - SIN SUBSIDIO' days: 10, legal_state: 'CARTA DE RATIFICACION ' },
# { name: 'BANCOLOMBIA - SIN SUBSIDIO' days: 3, legal_state: 'ESTUDIO TITULOS' },
# { name: 'BANCOLOMBIA - SIN SUBSIDIO' days: 1, legal_state: 'ELAB ESCRITURACION' },
# { name: 'BANCOLOMBIA - SIN SUBSIDIO' days: 5, legal_state: 'REVISION FIDUCIA' },
# { name: 'BANCOLOMBIA - SIN SUBSIDIO' days: 5, legal_state: 'FIRMA ESC. CLIENTE' },
# { name: 'BANCOLOMBIA - SIN SUBSIDIO' days: , legal_state: 'NUMERACION ESCRITURA' },
# { name: 'BANCOLOMBIA - SIN SUBSIDIO' days: 1, legal_state: 'FIRMA ESC. CONSTRUCTORA' },
# { name: 'BANCOLOMBIA - SIN SUBSIDIO' days: 3, legal_state: 'FIRMA FIDUCIA' },
# { name: 'BANCOLOMBIA - SIN SUBSIDIO' days: 5, legal_state: 'FIRMA BANCO CONSTRUCTOR' },
# { name: 'BANCOLOMBIA - SIN SUBSIDIO' days: 3, legal_state: 'FIRMA BANCO HIPOTECANTE' },
# { name: 'BANCOLOMBIA - SIN SUBSIDIO' days: 5, legal_state: 'PROTOCOLIZACION' },
# { name: 'BANCOLOMBIA - SIN SUBSIDIO' days: , legal_state: 'LIQUIDACION' },
# { name: 'BANCOLOMBIA - SIN SUBSIDIO' days: 3, legal_state: 'ENTRADA DE REGISTRO' },
# { name: 'BANCOLOMBIA - SIN SUBSIDIO' days: 5, legal_state: 'RADICADO EN ESPERA DE DESEMBOLSO' },
# { name: 'BANCOLOMBIA - SIN SUBSIDIO' days: , legal_state: 'SALIDA DE REGISTRO' },
# { name: 'BANCOLOMBIA - SIN SUBSIDIO' days: 3, legal_state: 'ENTREGA DE VIVIENDA' },
# { name: 'BANCOLOMBIA - SUBSIDIO CAJA' days: 15, legal_state: 'PREAPROB Y CONSEC' },
# { name: 'BANCOLOMBIA - SUBSIDIO CAJA' days: , legal_state: 'APROBADO ' },
# { name: 'BANCOLOMBIA - SUBSIDIO CAJA' days: 3, legal_state: 'AVALUO FINAL' },
# { name: 'BANCOLOMBIA - SUBSIDIO CAJA' days: 10, legal_state: 'CARTA DE RATIFICACION ' },
# { name: 'BANCOLOMBIA - SUBSIDIO CAJA' days: 3, legal_state: 'ESTUDIO TITULOS' },
# { name: 'BANCOLOMBIA - SUBSIDIO CAJA' days: 1, legal_state: 'ELAB ESCRITURACION' },
# { name: 'BANCOLOMBIA - SUBSIDIO CAJA' days: 5, legal_state: 'REVISION FIDUCIA' },
# { name: 'BANCOLOMBIA - SUBSIDIO CAJA' days: 5, legal_state: 'FIRMA ESC. CLIENTE' },
# { name: 'BANCOLOMBIA - SUBSIDIO CAJA' days: , legal_state: 'NUMERACION ESCRITURA' },
# { name: 'BANCOLOMBIA - SUBSIDIO CAJA' days: 1, legal_state: 'FIRMA ESC. CONSTRUCTORA' },
# { name: 'BANCOLOMBIA - SUBSIDIO CAJA' days: 3, legal_state: 'FIRMA FIDUCIA' },
# { name: 'BANCOLOMBIA - SUBSIDIO CAJA' days: 5, legal_state: 'FIRMA BANCO CONSTRUCTOR' },
# { name: 'BANCOLOMBIA - SUBSIDIO CAJA' days: 3, legal_state: 'FIRMA BANCO HIPOTECANTE' },
# { name: 'BANCOLOMBIA - SUBSIDIO CAJA' days: 5, legal_state: 'PROTOCOLIZACION' },
# { name: 'BANCOLOMBIA - SUBSIDIO CAJA' days: , legal_state: 'LIQUIDACION' },
# { name: 'BANCOLOMBIA - SUBSIDIO CAJA' days: 3, legal_state: 'ENTRADA DE REGISTRO' },
# { name: 'BANCOLOMBIA - SUBSIDIO CAJA' days: 5, legal_state: 'RADICADO EN ESPERA DE DESEMBOLSO' },
# { name: 'BANCOLOMBIA - SUBSIDIO CAJA' days: 3, legal_state: 'ENTREGA DE VIVIENDA' },
# { name: 'BANCOLOMBIA - SUBSIDIO CAJA' days: 10, legal_state: 'SALIDA DE REGISTRO' },
# { name: 'BANCOLOMBIA - SUBSIDIO CAJA' days: , legal_state: 'ACLARATORIA AL SUBSIDIO' },
# { name: 'BANCOLOMBIA - SUBSIDIO CAJA' days: 19, legal_state: 'SUBSIDIO RADICADO' },
# { name: 'BANCOLOMBIA - MCY' days: 15, legal_state: 'PREAPROB Y CONSEC' },
# { name: 'BANCOLOMBIA - MCY' days: , legal_state: 'APROBADO ' },
# { name: 'BANCOLOMBIA - MCY' days: 3, legal_state: 'AVALUO FINAL' },
# { name: 'BANCOLOMBIA - MCY' days: 10, legal_state: 'CARTA DE RATIFICACION ' },
# { name: 'BANCOLOMBIA - MCY' days: 15, legal_state: 'EN ESPERA DE RESOLUCION MCY (PROCESO 027)' },
# { name: 'BANCOLOMBIA - MCY' days: 3, legal_state: 'ESTUDIO TITULOS' },
# { name: 'BANCOLOMBIA - MCY' days: 1, legal_state: 'ELAB ESCRITURACION' },
# { name: 'BANCOLOMBIA - MCY' days: 5, legal_state: 'REVISION FIDUCIA' },
# { name: 'BANCOLOMBIA - MCY' days: 5, legal_state: 'FIRMA ESC. CLIENTE' },
# { name: 'BANCOLOMBIA - MCY' days: , legal_state: 'NUMERACION ESCRITURA' },
# { name: 'BANCOLOMBIA - MCY' days: 1, legal_state: 'FIRMA ESC. CONSTRUCTORA' },
# { name: 'BANCOLOMBIA - MCY' days: 3, legal_state: 'FIRMA FIDUCIA' },
# { name: 'BANCOLOMBIA - MCY' days: 5, legal_state: 'FIRMA BANCO CONSTRUCTOR' },
# { name: 'BANCOLOMBIA - MCY' days: 3, legal_state: 'FIRMA BANCO HIPOTECANTE' },
# { name: 'BANCOLOMBIA - MCY' days: 5, legal_state: 'PROTOCOLIZACION' },
# { name: 'BANCOLOMBIA - MCY' days: , legal_state: 'LIQUIDACION' },
# { name: 'BANCOLOMBIA - MCY' days: 3, legal_state: 'ENTRADA DE REGISTRO' },
# { name: 'BANCOLOMBIA - MCY' days: 5, legal_state: 'RADICADO EN ESPERA DE DESEMBOLSO' },
# { name: 'BANCOLOMBIA - MCY' days: 28, legal_state: 'SUBSIDIO RADICADO' },
# { name: 'BANCOLOMBIA - MCY' days: 3, legal_state: 'ENTREGA DE VIVIENDA' },
# { name: 'BANCOLOMBIA - SUBSIDIO CAJA Y MCY' days: 15, legal_state: 'PREAPROB Y CONSEC' },
# { name: 'BANCOLOMBIA - SUBSIDIO CAJA Y MCY' days: , legal_state: 'APROBADO ' },
# { name: 'BANCOLOMBIA - SUBSIDIO CAJA Y MCY' days: 3, legal_state: 'AVALUO FINAL' },
# { name: 'BANCOLOMBIA - SUBSIDIO CAJA Y MCY' days: 10, legal_state: 'CARTA DE RATIFICACION ' },
# { name: 'BANCOLOMBIA - SUBSIDIO CAJA Y MCY' days: 15, legal_state: 'EN ESPERA DE RESOLUCION MCY (PROCESO 027)' },
# { name: 'BANCOLOMBIA - SUBSIDIO CAJA Y MCY' days: 3, legal_state: 'ESTUDIO TITULOS' },
# { name: 'BANCOLOMBIA - SUBSIDIO CAJA Y MCY' days: 1, legal_state: 'ELAB ESCRITURACION' },
# { name: 'BANCOLOMBIA - SUBSIDIO CAJA Y MCY' days: 5, legal_state: 'REVISION FIDUCIA' },
# { name: 'BANCOLOMBIA - SUBSIDIO CAJA Y MCY' days: 5, legal_state: 'FIRMA ESC. CLIENTE' },
# { name: 'BANCOLOMBIA - SUBSIDIO CAJA Y MCY' days: , legal_state: 'NUMERACION ESCRITURA' },
# { name: 'BANCOLOMBIA - SUBSIDIO CAJA Y MCY' days: 1, legal_state: 'FIRMA ESC. CONSTRUCTORA' },
# { name: 'BANCOLOMBIA - SUBSIDIO CAJA Y MCY' days: 3, legal_state: 'FIRMA FIDUCIA' },
# { name: 'BANCOLOMBIA - SUBSIDIO CAJA Y MCY' days: 5, legal_state: 'FIRMA BANCO CONSTRUCTOR' },
# { name: 'BANCOLOMBIA - SUBSIDIO CAJA Y MCY' days: 3, legal_state: 'FIRMA BANCO HIPOTECANTE' },
# { name: 'BANCOLOMBIA - SUBSIDIO CAJA Y MCY' days: 5, legal_state: 'PROTOCOLIZACION' },
# { name: 'BANCOLOMBIA - SUBSIDIO CAJA Y MCY' days: , legal_state: 'LIQUIDACION' },
# { name: 'BANCOLOMBIA - SUBSIDIO CAJA Y MCY' days: 3, legal_state: 'ENTRADA DE REGISTRO' },
# { name: 'BANCOLOMBIA - SUBSIDIO CAJA Y MCY' days: 5, legal_state: 'RADICADO EN ESPERA DE DESEMBOLSO' },
# { name: 'BANCOLOMBIA - SUBSIDIO CAJA Y MCY' days: 3, legal_state: 'ENTREGA DE VIVIENDA' },
# { name: 'BANCOLOMBIA - SUBSIDIO CAJA Y MCY' days: 10, legal_state: 'SALIDA DE REGISTRO' },
# { name: 'BANCOLOMBIA - SUBSIDIO CAJA Y MCY' days: , legal_state: 'ACLARATORIA AL SUBSIDIO' },
# { name: 'BANCOLOMBIA - SUBSIDIO CAJA Y MCY' days: 19, legal_state: 'SUBSIDIO RADICADO' },
# { name: 'OTROS - SIN SUBSIDIO' days: 15, legal_state: 'PREAPROB Y CONSEC' },
# { name: 'OTROS - SIN SUBSIDIO' days: , legal_state: 'APROBADO ' },
# { name: 'OTROS - SIN SUBSIDIO' days: 7, legal_state: 'AVALUO FINAL' },
# { name: 'OTROS - SIN SUBSIDIO' days: 8, legal_state: 'ESTUDIO TITULOS' },
# { name: 'OTROS - SIN SUBSIDIO' days: , legal_state: 'CARTA DE RATIFICACION ' },
# { name: 'OTROS - SIN SUBSIDIO' days: 1, legal_state: 'ELAB ESCRITURACION' },
# { name: 'OTROS - SIN SUBSIDIO' days: 5, legal_state: 'REVISION FIDUCIA' },
# { name: 'OTROS - SIN SUBSIDIO' days: 5, legal_state: 'FIRMA ESC. CLIENTE' },
# { name: 'OTROS - SIN SUBSIDIO' days: , legal_state: 'NUMERACION ESCRITURA' },
# { name: 'OTROS - SIN SUBSIDIO' days: 1, legal_state: 'FIRMA ESC. CONSTRUCTORA' },
# { name: 'OTROS - SIN SUBSIDIO' days: 2, legal_state: 'FIRMA FIDUCIA' },
# { name: 'OTROS - SIN SUBSIDIO' days: 5, legal_state: 'FIRMA BANCO CONSTRUCTOR' },
# { name: 'OTROS - SIN SUBSIDIO' days: 5, legal_state: 'FIRMA BANCO HIPOTECANTE' },
# { name: 'OTROS - SIN SUBSIDIO' days: 5, legal_state: 'PROTOCOLIZACION' },
# { name: 'OTROS - SIN SUBSIDIO' days: , legal_state: 'LIQUIDACION' },
# { name: 'OTROS - SIN SUBSIDIO' days: 3, legal_state: 'ENTRADA DE REGISTRO' },
# { name: 'OTROS - SIN SUBSIDIO' days: 10, legal_state: 'SALIDA DE REGISTRO' },
# { name: 'OTROS - SIN SUBSIDIO' days: 7, legal_state: 'RADICADO EN ESPERA DE DESEMBOLSO' },
# { name: 'OTROS - SIN SUBSIDIO' days: 3, legal_state: 'ENTREGA DE VIVIENDA' },
# { name: 'OTROS - SUBSIDIO CAJA' days: 15, legal_state: 'PREAPROB Y CONSEC' },
# { name: 'OTROS - SUBSIDIO CAJA' days: , legal_state: 'APROBADO ' },
# { name: 'OTROS - SUBSIDIO CAJA' days: 7, legal_state: 'AVALUO FINAL' },
# { name: 'OTROS - SUBSIDIO CAJA' days: 8, legal_state: 'ESTUDIO TITULOS' },
# { name: 'OTROS - SUBSIDIO CAJA' days: , legal_state: 'CARTA DE RATIFICACION ' },
# { name: 'OTROS - SUBSIDIO CAJA' days: 1, legal_state: 'ELAB ESCRITURACION' },
# { name: 'OTROS - SUBSIDIO CAJA' days: 5, legal_state: 'REVISION FIDUCIA' },
# { name: 'OTROS - SUBSIDIO CAJA' days: 5, legal_state: 'FIRMA ESC. CLIENTE' },
# { name: 'OTROS - SUBSIDIO CAJA' days: , legal_state: 'NUMERACION ESCRITURA' },
# { name: 'OTROS - SUBSIDIO CAJA' days: 1, legal_state: 'FIRMA ESC. CONSTRUCTORA' },
# { name: 'OTROS - SUBSIDIO CAJA' days: 2, legal_state: 'FIRMA FIDUCIA' },
# { name: 'OTROS - SUBSIDIO CAJA' days: 5, legal_state: 'FIRMA BANCO CONSTRUCTOR' },
# { name: 'OTROS - SUBSIDIO CAJA' days: 5, legal_state: 'FIRMA BANCO HIPOTECANTE' },
# { name: 'OTROS - SUBSIDIO CAJA' days: 5, legal_state: 'PROTOCOLIZACION' },
# { name: 'OTROS - SUBSIDIO CAJA' days: , legal_state: 'LIQUIDACION' },
# { name: 'OTROS - SUBSIDIO CAJA' days: 3, legal_state: 'ENTRADA DE REGISTRO' },
# { name: 'OTROS - SUBSIDIO CAJA' days: 10, legal_state: 'SALIDA DE REGISTRO' },
# { name: 'OTROS - SUBSIDIO CAJA' days: 7, legal_state: 'RADICADO EN ESPERA DE DESEMBOLSO' },
# { name: 'OTROS - SUBSIDIO CAJA' days: , legal_state: 'ACLARATORIA AL SUBSIDIO' },
# { name: 'OTROS - SUBSIDIO CAJA' days: 19, legal_state: 'SUBSIDIO RADICADO' },
# { name: 'OTROS - SUBSIDIO CAJA' days: 3, legal_state: 'ENTREGA DE VIVIENDA' },
# { name: 'OTROS - MCY' days: 15, legal_state: 'PREAPROB Y CONSEC' },
# { name: 'OTROS - MCY' days: , legal_state: 'APROBADO ' },
# { name: 'OTROS - MCY' days: 7, legal_state: 'AVALUO FINAL' },
# { name: 'OTROS - MCY' days: 8, legal_state: 'ESTUDIO TITULOS' },
# { name: 'OTROS - MCY' days: , legal_state: 'CARTA DE RATIFICACION ' },
# { name: 'OTROS - MCY' days: 15, legal_state: 'EN ESPERA DE RESOLUCION MCY (PROCESO 027)' },
# { name: 'OTROS - MCY' days: 1, legal_state: 'ELAB ESCRITURACION' },
# { name: 'OTROS - MCY' days: 5, legal_state: 'REVISION FIDUCIA' },
# { name: 'OTROS - MCY' days: 5, legal_state: 'FIRMA ESC. CLIENTE' },
# { name: 'OTROS - MCY' days: , legal_state: 'NUMERACION ESCRITURA' },
# { name: 'OTROS - MCY' days: 1, legal_state: 'FIRMA ESC. CONSTRUCTORA' },
# { name: 'OTROS - MCY' days: 2, legal_state: 'FIRMA FIDUCIA' },
# { name: 'OTROS - MCY' days: 5, legal_state: 'FIRMA BANCO CONSTRUCTOR' },
# { name: 'OTROS - MCY' days: 5, legal_state: 'FIRMA BANCO HIPOTECANTE' },
# { name: 'OTROS - MCY' days: 5, legal_state: 'PROTOCOLIZACION' },
# { name: 'OTROS - MCY' days: , legal_state: 'LIQUIDACION' },
# { name: 'OTROS - MCY' days: 3, legal_state: 'ENTRADA DE REGISTRO' },
# { name: 'OTROS - MCY' days: 10, legal_state: 'SALIDA DE REGISTRO' },
# { name: 'OTROS - MCY' days: 7, legal_state: 'RADICADO EN ESPERA DE DESEMBOLSO' },
# { name: 'OTROS - MCY' days: 28, legal_state: 'SUBSIDIO RADICADO' },
# { name: 'OTROS - MCY' days: 3, legal_state: 'ENTREGA DE VIVIENDA' },
# { name: 'OTROS - SUBSIDIO CAJA Y MCY' days: 15, legal_state: 'PREAPROB Y CONSEC' },
# { name: 'OTROS - SUBSIDIO CAJA Y MCY' days: , legal_state: 'APROBADO ' },
# { name: 'OTROS - SUBSIDIO CAJA Y MCY' days: 7, legal_state: 'AVALUO FINAL' },
# { name: 'OTROS - SUBSIDIO CAJA Y MCY' days: 8, legal_state: 'ESTUDIO TITULOS' },
# { name: 'OTROS - SUBSIDIO CAJA Y MCY' days: , legal_state: 'CARTA DE RATIFICACION ' },
# { name: 'OTROS - SUBSIDIO CAJA Y MCY' days: 15, legal_state: 'EN ESPERA DE RESOLUCION MCY (PROCESO 027)' },
# { name: 'OTROS - SUBSIDIO CAJA Y MCY' days: 1, legal_state: 'ELAB ESCRITURACION' },
# { name: 'OTROS - SUBSIDIO CAJA Y MCY' days: 5, legal_state: 'REVISION FIDUCIA' },
# { name: 'OTROS - SUBSIDIO CAJA Y MCY' days: 5, legal_state: 'FIRMA ESC. CLIENTE' },
# { name: 'OTROS - SUBSIDIO CAJA Y MCY' days: , legal_state: 'NUMERACION ESCRITURA' },
# { name: 'OTROS - SUBSIDIO CAJA Y MCY' days: 1, legal_state: 'FIRMA ESC. CONSTRUCTORA' },
# { name: 'OTROS - SUBSIDIO CAJA Y MCY' days: 2, legal_state: 'FIRMA FIDUCIA' },
# { name: 'OTROS - SUBSIDIO CAJA Y MCY' days: 5, legal_state: 'FIRMA BANCO CONSTRUCTOR' },
# { name: 'OTROS - SUBSIDIO CAJA Y MCY' days: 5, legal_state: 'FIRMA BANCO HIPOTECANTE' },
# { name: 'OTROS - SUBSIDIO CAJA Y MCY' days: 5, legal_state: 'PROTOCOLIZACION' },
# { name: 'OTROS - SUBSIDIO CAJA Y MCY' days: , legal_state: 'LIQUIDACION' },
# { name: 'OTROS - SUBSIDIO CAJA Y MCY' days: 3, legal_state: 'ENTRADA DE REGISTRO' },
# { name: 'OTROS - SUBSIDIO CAJA Y MCY' days: 10, legal_state: 'SALIDA DE REGISTRO' },
# { name: 'OTROS - SUBSIDIO CAJA Y MCY' days: 7, legal_state: 'RADICADO EN ESPERA DE DESEMBOLSO' },
# { name: 'OTROS - SUBSIDIO CAJA Y MCY' days: , legal_state: 'ACLARATORIA AL SUBSIDIO' },
# { name: 'OTROS - SUBSIDIO CAJA Y MCY' days: 19, legal_state: 'SUBSIDIO RADICADO' },
# { name: 'OTROS - SUBSIDIO CAJA Y MCY' days: 3, legal_state: 'ENTREGA DE VIVIENDA' },
# { name: 'F.N.A. - SIN SUBSIDIO' days: 15, legal_state: 'PREAPROB Y CONSEC' },
# { name: 'F.N.A. - SIN SUBSIDIO' days: , legal_state: 'APROBADO ' },
# { name: 'F.N.A. - SIN SUBSIDIO' days: 30, legal_state: 'AVALUO FINAL' },
# { name: 'F.N.A. - SIN SUBSIDIO' days: 20, legal_state: 'ESTUDIO TITULOS' },
# { name: 'F.N.A. - SIN SUBSIDIO' days: 1, legal_state: 'ELAB ESCRITURACION' },
# { name: 'F.N.A. - SIN SUBSIDIO' days: 5, legal_state: 'REVISION FIDUCIA' },
# { name: 'F.N.A. - SIN SUBSIDIO' days: 5, legal_state: 'FIRMA ESC. CLIENTE' },
# { name: 'F.N.A. - SIN SUBSIDIO' days: , legal_state: 'NUMERACION ESCRITURA' },
# { name: 'F.N.A. - SIN SUBSIDIO' days: 1, legal_state: 'FIRMA ESC. CONSTRUCTORA' },
# { name: 'F.N.A. - SIN SUBSIDIO' days: 2, legal_state: 'FIRMA FIDUCIA' },
# { name: 'F.N.A. - SIN SUBSIDIO' days: 30, legal_state: 'FIRMA BANCO CONSTRUCTOR' },
# { name: 'F.N.A. - SIN SUBSIDIO' days: 7, legal_state: 'FIRMA BANCO HIPOTECANTE' },
# { name: 'F.N.A. - SIN SUBSIDIO' days: 5, legal_state: 'PROTOCOLIZACION' },
# { name: 'F.N.A. - SIN SUBSIDIO' days: , legal_state: 'LIQUIDACION' },
# { name: 'F.N.A. - SIN SUBSIDIO' days: 3, legal_state: 'ENTRADA DE REGISTRO' },
# { name: 'F.N.A. - SIN SUBSIDIO' days: 10, legal_state: 'SALIDA DE REGISTRO' },
# { name: 'F.N.A. - SIN SUBSIDIO' days: 8, legal_state: 'RADICADO EN ESPERA DE DESEMBOLSO' },
# { name: 'F.N.A. - SIN SUBSIDIO' days: 3, legal_state: 'ENTREGA DE VIVIENDA' },
# { name: 'F.N.A. - SUBSIDIO CAJA' days: 15, legal_state: 'PREAPROB Y CONSEC' },
# { name: 'F.N.A. - SUBSIDIO CAJA' days: , legal_state: 'APROBADO ' },
# { name: 'F.N.A. - SUBSIDIO CAJA' days: 30, legal_state: 'AVALUO FINAL' },
# { name: 'F.N.A. - SUBSIDIO CAJA' days: 20, legal_state: 'ESTUDIO TITULOS' },
# { name: 'F.N.A. - SUBSIDIO CAJA' days: 1, legal_state: 'ELAB ESCRITURACION' },
# { name: 'F.N.A. - SUBSIDIO CAJA' days: 5, legal_state: 'REVISION FIDUCIA' },
# { name: 'F.N.A. - SUBSIDIO CAJA' days: 5, legal_state: 'FIRMA ESC. CLIENTE' },
# { name: 'F.N.A. - SUBSIDIO CAJA' days: , legal_state: 'NUMERACION ESCRITURA' },
# { name: 'F.N.A. - SUBSIDIO CAJA' days: 1, legal_state: 'FIRMA ESC. CONSTRUCTORA' },
# { name: 'F.N.A. - SUBSIDIO CAJA' days: 2, legal_state: 'FIRMA FIDUCIA' },
# { name: 'F.N.A. - SUBSIDIO CAJA' days: 2, legal_state: 'FIRMA BANCO CONSTRUCTOR' },
# { name: 'F.N.A. - SUBSIDIO CAJA' days: 7, legal_state: 'FIRMA BANCO HIPOTECANTE' },
# { name: 'F.N.A. - SUBSIDIO CAJA' days: 5, legal_state: 'PROTOCOLIZACION' },
# { name: 'F.N.A. - SUBSIDIO CAJA' days: , legal_state: 'LIQUIDACION' },
# { name: 'F.N.A. - SUBSIDIO CAJA' days: 3, legal_state: 'ENTRADA DE REGISTRO' },
# { name: 'F.N.A. - SUBSIDIO CAJA' days: 10, legal_state: 'SALIDA DE REGISTRO' },
# { name: 'F.N.A. - SUBSIDIO CAJA' days: 8, legal_state: 'RADICADO EN ESPERA DE DESEMBOLSO' },
# { name: 'F.N.A. - SUBSIDIO CAJA' days: , legal_state: 'ACLARATORIA AL SUBSIDIO' },
# { name: 'F.N.A. - SUBSIDIO CAJA' days: 19, legal_state: 'SUBSIDIO RADICADO' },
# { name: 'F.N.A. - SUBSIDIO CAJA' days: 3, legal_state: 'ENTREGA DE VIVIENDA' },
# { name: 'F.N.A. - MCY' days: 15, legal_state: 'PREAPROB Y CONSEC' },
# { name: 'F.N.A. - MCY' days: , legal_state: 'APROBADO ' },
# { name: 'F.N.A. - MCY' days: 30, legal_state: 'AVALUO FINAL' },
# { name: 'F.N.A. - MCY' days: 20, legal_state: 'ESTUDIO TITULOS' },
# { name: 'F.N.A. - MCY' days: 15, legal_state: 'EN ESPERA DE RESOLUCION MCY (PROCESO 027)' },
# { name: 'F.N.A. - MCY' days: 1, legal_state: 'ELAB ESCRITURACION' },
# { name: 'F.N.A. - MCY' days: 5, legal_state: 'REVISION FIDUCIA' },
# { name: 'F.N.A. - MCY' days: 5, legal_state: 'FIRMA ESC. CLIENTE' },
# { name: 'F.N.A. - MCY' days: , legal_state: 'NUMERACION ESCRITURA' },
# { name: 'F.N.A. - MCY' days: 1, legal_state: 'FIRMA ESC. CONSTRUCTORA' },
# { name: 'F.N.A. - MCY' days: 2, legal_state: 'FIRMA FIDUCIA' },
# { name: 'F.N.A. - MCY' days: 30, legal_state: 'FIRMA BANCO CONSTRUCTOR' },
# { name: 'F.N.A. - MCY' days: 7, legal_state: 'FIRMA BANCO HIPOTECANTE' },
# { name: 'F.N.A. - MCY' days: 5, legal_state: 'PROTOCOLIZACION' },
# { name: 'F.N.A. - MCY' days: , legal_state: 'LIQUIDACION' },
# { name: 'F.N.A. - MCY' days: 3, legal_state: 'ENTRADA DE REGISTRO' },
# { name: 'F.N.A. - MCY' days: 10, legal_state: 'SALIDA DE REGISTRO' },
# { name: 'F.N.A. - MCY' days: 8, legal_state: 'RADICADO EN ESPERA DE DESEMBOLSO' },
# { name: 'F.N.A. - MCY' days: 28, legal_state: 'SUBSIDIO RADICADO' },
# { name: 'F.N.A. - MCY' days: 3, legal_state: 'ENTREGA DE VIVIENDA' },
# { name: 'F.N.A. - SUBSIDIO CAJA Y MCY' days: 15, legal_state: 'PREAPROB Y CONSEC' },
# { name: 'F.N.A. - SUBSIDIO CAJA Y MCY' days: , legal_state: 'APROBADO ' },
# { name: 'F.N.A. - SUBSIDIO CAJA Y MCY' days: 30, legal_state: 'AVALUO FINAL' },
# { name: 'F.N.A. - SUBSIDIO CAJA Y MCY' days: 20, legal_state: 'ESTUDIO TITULOS' },
# { name: 'F.N.A. - SUBSIDIO CAJA Y MCY' days: 15, legal_state: 'EN ESPERA DE RESOLUCION MCY (PROCESO 027)' },
# { name: 'F.N.A. - SUBSIDIO CAJA Y MCY' days: 5, legal_state: 'REVISION FIDUCIA' },
# { name: 'F.N.A. - SUBSIDIO CAJA Y MCY' days: 5, legal_state: 'FIRMA ESC. CLIENTE' },
# { name: 'F.N.A. - SUBSIDIO CAJA Y MCY' days: , legal_state: 'NUMERACION ESCRITURA' },
# { name: 'F.N.A. - SUBSIDIO CAJA Y MCY' days: 1, legal_state: 'FIRMA ESC. CONSTRUCTORA' },
# { name: 'F.N.A. - SUBSIDIO CAJA Y MCY' days: 2, legal_state: 'FIRMA FIDUCIA' },
# { name: 'F.N.A. - SUBSIDIO CAJA Y MCY' days: 30, legal_state: 'FIRMA BANCO CONSTRUCTOR' },
# { name: 'F.N.A. - SUBSIDIO CAJA Y MCY' days: 7, legal_state: 'FIRMA BANCO HIPOTECANTE' },
# { name: 'F.N.A. - SUBSIDIO CAJA Y MCY' days: 5, legal_state: 'PROTOCOLIZACION' },
# { name: 'F.N.A. - SUBSIDIO CAJA Y MCY' days: , legal_state: 'LIQUIDACION' },
# { name: 'F.N.A. - SUBSIDIO CAJA Y MCY' days: 3, legal_state: 'ENTRADA DE REGISTRO' },
# { name: 'F.N.A. - SUBSIDIO CAJA Y MCY' days: 10, legal_state: 'SALIDA DE REGISTRO' },
# { name: 'F.N.A. - SUBSIDIO CAJA Y MCY' days: 8, legal_state: 'RADICADO EN ESPERA DE DESEMBOLSO' },
# { name: 'F.N.A. - SUBSIDIO CAJA Y MCY' days: , legal_state: 'ACLARATORIA AL SUBSIDIO' },
# { name: 'F.N.A. - SUBSIDIO CAJA Y MCY' days: 19, legal_state: 'SUBSIDIO RADICADO' },
# { name: 'F.N.A. - SUBSIDIO CAJA Y MCY' days: 3, legal_state: 'ENTREGA DE VIVIENDA' },
# { name: 'VENTA DIRECTA - SUBSIDIO CAJA' days: 1, legal_state: 'ELAB ESCRITURACION' },
# { name: 'VENTA DIRECTA - SUBSIDIO CAJA' days: 5, legal_state: 'REVISION FIDUCIA' },
# { name: 'VENTA DIRECTA - SUBSIDIO CAJA' days: 5, legal_state: 'FIRMA ESC. CLIENTE' },
# { name: 'VENTA DIRECTA - SUBSIDIO CAJA' days: , legal_state: 'NUMERACION ESCRITURA' },
# { name: 'VENTA DIRECTA - SUBSIDIO CAJA' days: 1, legal_state: 'FIRMA ESC. CONSTRUCTORA' },
# { name: 'VENTA DIRECTA - SUBSIDIO CAJA' days: 2, legal_state: 'FIRMA FIDUCIA' },
# { name: 'VENTA DIRECTA - SUBSIDIO CAJA' days: 15, legal_state: 'FIRMA BANCO CONSTRUCTOR' },
# { name: 'VENTA DIRECTA - SUBSIDIO CAJA' days: 5, legal_state: 'PROTOCOLIZACION' },
# { name: 'VENTA DIRECTA - SUBSIDIO CAJA' days: , legal_state: 'LIQUIDACION' },
# { name: 'VENTA DIRECTA - SUBSIDIO CAJA' days: 3, legal_state: 'ENTRADA DE REGISTRO' },
# { name: 'VENTA DIRECTA - SUBSIDIO CAJA' days: 10, legal_state: 'SALIDA DE REGISTRO' },
# { name: 'VENTA DIRECTA - SUBSIDIO CAJA' days: , legal_state: 'ACLARATORIA AL SUBSIDIO' },
# { name: 'VENTA DIRECTA - SUBSIDIO CAJA' days: 19, legal_state: 'SUBSIDIO RADICADO' },
# { name: 'VENTA DIRECTA - SUBSIDIO CAJA' days: 3, legal_state: 'ENTREGA DE VIVIENDA' },
# { name: 'VENTA DIRECTA - SIN SUBSIDIO' days: 1, legal_state: 'ELAB ESCRITURACION' },
# { name: 'VENTA DIRECTA - SIN SUBSIDIO' days: 5, legal_state: 'REVISION FIDUCIA' },
# { name: 'VENTA DIRECTA - SIN SUBSIDIO' days: 5, legal_state: 'FIRMA ESC. CLIENTE' },
# { name: 'VENTA DIRECTA - SIN SUBSIDIO' days: , legal_state: 'NUMERACION ESCRITURA' },
# { name: 'VENTA DIRECTA - SIN SUBSIDIO' days: 1, legal_state: 'FIRMA ESC. CONSTRUCTORA' },
# { name: 'VENTA DIRECTA - SIN SUBSIDIO' days: , legal_state: 'FIRMA FIDUCIA' },
# { name: 'VENTA DIRECTA - SIN SUBSIDIO' days: 15, legal_state: 'FIRMA BANCO CONSTRUCTOR' },
# { name: 'VENTA DIRECTA - SIN SUBSIDIO' days: 2, legal_state: 'PROTOCOLIZACION' },
# { name: 'VENTA DIRECTA - SIN SUBSIDIO' days: 5, legal_state: 'LIQUIDACION' },
# { name: 'VENTA DIRECTA - SIN SUBSIDIO' days: 3, legal_state: 'ENTRADA DE REGISTRO' },
# { name: 'VENTA DIRECTA - SIN SUBSIDIO' days: 10, legal_state: 'SALIDA DE REGISTRO' },
# { name: 'VENTA DIRECTA - SIN SUBSIDIO' days: 3, legal_state: 'ENTREGA DE VIVIENDA' },
