LS_EQUIVALENTS = {"A REUBICAR": "A REUBICAR",
                  "ACLARATORIA AL SUBSIDIO": "ACLARATORIA AL SUBSIDIO",
                  "APROBADO": "APROBADO ",
                  "APROBADO - ACTUALIZACION": "APROBADO ",
                  "AVALUOS": "AVALUO",
                  "AVALUO - ACTUALIZACION": "AVALUO",
                  "AVALUO FINAL OTROS BANCOS": "AVALUO",
                  "AVALUO PRELIMINAR": "AVALUO",
                  "CARTA DE NOVEDAD": "CARTA DE NOVEDAD",
                  "CARTA DE RATIFICACION": "CARTA DE RATIFICACION ",
                  "CASO INMOBILIARIA": "CASO INMOBILIARIA",
                  "DESEMBOLSADO": "DESEMBOLSADO",
                  "ELAB ESCRITURA": "ELAB ESCRITURACION",
                  "ELAB ESCRITURA CON SALDO": "ELAB ESCRITURACION",
                  "EN ESPERA DE RESOLUCION PARA ENVIAR A ESCRITURAR": "EN ESPERA DE RESOLUCION MCY (PROCESO 027)",
                  "EN ESPERA RESOLUCION MCY PARA ESTUDIO TITULO": "EN ESPERA DE RESOLUCION MCY (PROCESO 027)",
                  "ENTRADA REGISTRO": "REGISTRO",
                  "ENTREGADA": "ENTREGA DE VIVIENDA",
                  "ESTUDIO TITULOS": "ESTUDIO TITULO (PROCESO 027)",
                  "FIRMA BANCO": "FIRMA",
                  "FIRMA BANCO LIBERACION": "FIRMA",
                  "PAGO DE PRORRATA-VTA DIRECTA": "FIRMA",
                  "FIRMA ESCRITURA": "FIRMA",
                  "FIRMA FIDUCIA": "FIRMA",
                  "LIBRE": "LIBRE",
                  "LIBRE INVERSION": "LIBRE INVERSION",
                  "LIQUIDACION": "LIQUIDACION",
                  "NEGADO": "NEGADO",
                  "PREAPROB Y CONSEC": "PREAPROB Y CONSEC",
                  "PROTOCOLIZACION": "PROTOCOLIZACION",
                  "RADICADO EN BANCO Y CAJA": "RADICADO EN ESPERA DE DESEMBOLSO",
                  "RADICADO EN ESPERA DE DESEMBOLSO": "RADICADO EN ESPERA DE DESEMBOLSO",
                  "REVISION FIDUCIA": "REVISION FIDUCIA",
                  "SALDO EN EFECTIVO": "SALDO EN EFECTIVO",
                  "SALIDA REGISTRO": "REGISTRO",
                  "SUBSIDIO RADICADO": "SUBSIDIO RADICADO",
                  "TRAMITE": "TRAMITE",
                  "TRAMITE - ACTUALIZACION": "TRAMITE",
                  "VENDIDA": "VENDIDA",
                  "PRED Y VALOR": "PRED Y VALOR",
                  "ESPERANDO AVALUO FINAL PARA EL DESEMBOLSO": "AVALUO",
                  "A DESISTIR": "A DESISTIR"
                }
